aiogram/types/inline_keyboard.py
aiogram/types/reply_keyboard.py

While writing a bot, I've caught an error which solves replacing 'to_json' by 'to_python'.

Fix error replacing 'to_json' by 'to_python'

---

aiogram/bot/bot.py

Just discovered that aiogram has not got full Bot API 3.6 support (parse mode for all media captions).
+ minor typography fixes
And I'm not sure about parse mode in Inline answers...

Add pasrse_mode to all medias (Bot API 3.6 support)

---

aiogram/utils/executor.py

Fix error: web.run_app() got an unexpected keyword argument 'loop'
Cause:
But:

BugFix: web.run_app doesn't wait for loop kwarg

---

aiogram/types/message.py

Fix for issue https://github.com/aiogram/aiogram/issues/26
Venue Message consists of location and venue fields. 
If you check location first - you always set message type = location

Swap around checking of VENUE and LOCATION content

---

aiogram/utils/markdown.py

can be used to add images to text posts as preview

New markdown method - hide_link

---

aiogram/types/reply_keyboard.py

Fix when add method taking multiple buttons was adding one button to a new row and then adding items to rows according to row_width

Fix ReplyKeyboardMarkup's add method

---

aiogram/types/chat.py

Once you get invite link for chat object - it will be cached

Chat.invite_link cache

---

aiogram/types/chat.py

Use this method to get chat link.
Private chat returns user link.
Other chat types return either username link (if they are public) or invite link (if they are private).

Add Chat.get_url() method

---

aiogram/utils/exceptions.py

Exception CantRestrictSelf happens if admin try to restrict self

CantRestrictSelf exception

---

aiogram/utils/json.py

fix pyCharm warning
'ujson' in try block with 'except ImportError' should also be defined in except block
This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.

Update json.py to fix pyCharm warning

---

aiogram/utils/exceptions.py

If bot without admin rights try to delete message it receive BadRequest: message can't be deleted

MessageCantBeDeleted exception

---

examples/middleware_and_antiflood.py

Added other *args to on_process_message()
```
Traceback (most recent call last):
File "/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in _process_polling_updates
for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
File "/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in process_updates
return await asyncio.gather(*tasks)
File "/python3.7/site-packages/aiogram/dispatcher/handler.py", line 99, in notify
response = await handler(*args, **partial_data)
File "/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 168, in process_update
return await self.message_handlers.notify(update.message)
File "/python3.7/site-packages/aiogram/dispatcher/handler.py", line 97, in notify
await …
```

Added other args for on_process_message()

---

aiogram/dispatcher/webhook.py
aiogram/utils/executor.py

Some applications already use `aiohttp.Application` in their code, so there is no need to create an additional application. This PR adds `aiogram.utils.executor.set_webhook` function that accepts `web_app` argument.
I used `aiogram.utils.executor.set_webhook` function in my bot KgJiraBot. You can reproduce my experience if you create an application of bot that creates `aiohttp.Application` and uses `aiogram.utils.executor.set_webhook`.
* Operating System: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
* Python version: Python 3.7
I didn't include tests because `aiogram.utils.executor` don't have tests at all.

Add aiogram.utils.executor.set_webhook

---

aiogram/dispatcher/dispatcher.py
aiogram/utils/executor.py

Bot can "clean" the updates by calling getUpdates method with a negative offset

Faster skip updates (calling getUpdates with a negative offset)

---

aiogram/bot/base.py

Fixes issue when domain name api.telegram.org rewritten on provider's DNS service.
Fixes #97 

DNS over socks proxy

---

aiogram/types/message.py

Related to #103
Message.edit_caption
Message.edit_media
Message.edit_reply_markup
At least, Message.edit_reply_markup will be useful with callback queries
```python
c.message.edit_reply_markup() # Will delete buttons
c.message.edit_reply_markup(reply_markup=...) # Pass new inline markup
```

Some useful Message edit functions

---

aiogram/types/base.py
tests/__init__.py
tests/test_message.py

I can create bot instance, then send message and then try to use helper method (for example msg.edit_text('text')). Now we have not clear exception: 'AttributeError: NoneType object has not attribute edit_message'.
This PR helps user to identify exception reason and recommends add bot instance to context manually.

Raise Exception if there's no bot instance in context

---

aiogram/contrib/fsm_storage/redis.py
aiogram/contrib/middlewares/i18n.py
aiogram/dispatcher/handler.py
aiogram/dispatcher/webhook.py
aiogram/types/encrypted_passport_element.py
aiogram/types/message.py
aiogram/types/passport_data.py
aiogram/types/venue.py
aiogram/utils/auth_widget.py
aiogram/utils/exceptions.py
aiogram/utils/mixins.py
examples/callback_data_factory.py
examples/payments.py
examples/webhook_example.py
tests/__init__.py
tests/test_dispatcher.py

- Add more await in RedisStorage and RedisStorage2
- Replace "send" with "reply" in some method's names
- Add "answer" method to Message
- Add "lazy_gettext" method to I18nMiddleware
- Reformat code

Some changes

---

aiogram/contrib/fsm_storage/files.py

JSONStorage isn't functioning properly at this moment. Once bot restarted, it doesn't consume info that was read during initialization: MemoryStorage is operating with "data" variable, but _FileStorage class puts loaded state to "_data".
- [+] Bug fix (non-breaking change which fixes an issue)
Simple example without _FileStorage class in the middle solves the issue:
```
class JSONStorage(MemoryStorage):
def __init__(self, path: typing.Union[pathlib.Path, str]):
"""
:param path: file path
"""
super(JSONStorage, self).__init__()
path = self.path = pathlib.Path(path)
try:
self.data = self.read(path)
except FileNotFoundError:
pass
async def close(self):
self.write(self.path)
await super(JSONStorage, self).close()
def read(self, path: pathlib.Path):
with path.open('r') as f:
return …
```

Fix FileStorage data reading

---

aiogram/contrib/fsm_storage/redis.py

Опечатка в RedisStorage2: вместо bucket функций вызывались data.
Это «Breaking change», поскольку меняет ключ обращения к редису, вероятно надо бы предупредить тех, кто пользуется и/или перенести на будущий релиз.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Typo: data -> bucket in update_bucket

---

aiogram/utils/exceptions.py
dev_requirements.txt
tests/test_bot.py

Makes InvalidQueryID conform to new telegram api responses
Adds new exception type MessageToReplyNotFound
Sets pytests `<4.6` according to https://github.com/pytest-dev/pytest/issues/5358
Splits FakeTelegram-based tests into parts (looks like they were failing because of context dirtying)

update exception matcher and fix tests

---

aiogram/dispatcher/handler.py

Send data from middlewares to filters
In middleware, I get a user object from the database, but it is not passed to filters.
Replaced
```data.update(await check_filters(handler_obj.filters, args))```
with
```data.update(await check_filters(handler_obj.filters, args + (data,)))```
as have suggested @gabbhack 
Fixes #124

Send data from middlewares to filters 

---

aiogram/contrib/fsm_storage/redis.py

- Added ttl settings in RedisStorage2
- Fixed _update_bucket_ method in RedisStorage2
- Updated docstrings
Fixes #139 
1. Copy files from [gist](https://gist.github.com/gabbhack/e963fe98118a72dab12999bfd5aff2ce)
2. Deploy it to heroku
3. Profit
* Heroku add-ons: [Heroku redis](https://elements.heroku.com/addons/heroku-redis)
* requirements: aioredis
* Python version: 3.7.3

Redis storage update

---

aiogram/dispatcher/handler.py

Reverts aiogram/aiogram#140
https://pastebin.com/6V75nkTp
``` python3 
future: <Task finished coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\Nike\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py:274> exception=TypeError('check() takes 2 positional arguments but 3 were given')>
Traceback (most recent call last):
File "C:\Users\Nike\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 282, in _process_polling_updates
for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
File "C:\Users\Nike\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 142, in process_updates
return await asyncio.gather(*tasks)
File …
```

Revert "Send data from middlewares to filters "

---

aiogram/contrib/middlewares/logging.py

Logged callback sender id instead of message sender id.
Added message_id
Result:
`Received callback query [ID] from user [ID] for message [ID] in chat [type:ID]`

logged callback sender id instead of message sender id

---

aiogram/contrib/fsm_storage/files.py

There is a bug that the file storages doesn't save the data after stop. [Here](https://github.com/aiogram/aiogram/issues/138#issuecomment-504660606) I described why it happens in details. In 2 words, the storages try to save data 2 times, and because of clearing after the first writing, the empty state is being saved on the disk. The solution I came up with is to perform writing only if the `self.data` is not empty. What's the reason to write if we have nothing to be stored? 
Fixes #138 
I tested it manually. Run [this](https://gist.github.com/Birdi7/ffb3077b89d81f897df0d51072a8dbbd) gist to ensure that my solution works.

Closes #138

---

examples/callback_data_factory_simple.py

Some users complain that the [basic example](examples/callback_data_factory.py) on callback data factory has too much information, which is excessive for the understanding the CBData factory concept itself (https://t.me/aiogram_ru/74478), so I created a simpler example which focuses on the concept of factory

Add simple example of usage of callback data factory

---

aiogram/bot/bot.py

thumb argument was ignored in Bot.send_audio method
fixed in compliance with other methods that have thumb argument

Fixed thumb for sendAudio

---

tests/test_filters.py

Add tests which check the functionality of the Text filter. In particular, modes equals, contains, startswith and endswith. Some tests are failed due to bug #169

Add tests for text filter

---

aiogram/contrib/middlewares/i18n.py

Add new parameter `enable_cache` to `i18nMiddleware.lazy_gettext`. Specifies if the value is cached after the first call of .value of LazyProxy object. 
Manually

Add enable_cache parameter to lazy_gettext

---

aiogram/dispatcher/filters/builtin.py
tests/test_filters.py

The current implementation of the Text filter doesn't allow an empty string as a string to match to. But, as suggested in [aiogram_ru#79691](https://t.me/aiogram_ru/79691), in inline query handler the empty string can be a value we got from user. As @JrooTJunior suggested in [aiogram_ru#79697](https://t.me/aiogram_ru/79697), I replaced checking from `bool` to `is None`, and added tests to check it
I added unit tests to every method of Text filter(equals, startswith, endswith, contains) to check for positive and negative results with ignore_case both `True` and `False`

Fix empty text filter

---

aiogram/dispatcher/filters/filters.py

The comments were in the wrong place. [Here](https://aiogram.readthedocs.io/en/latest/dispatcher/filters.html#aiogram.dispatcher.filters.filters.BoundFilter) the `default` parameter doesn't appear because of it. The descriptions of the `key` and `required` fields were wrong

Fix filter docs

---

aiogram/contrib/fsm_storage/mongo.py

Added Mongo storage support based on [aiomongo](https://github.com/ZeoAlliance/aiomongo)

Mongo storage

---

aiogram/dispatcher/filters/builtin.py
examples/text_filter_example.py
tests/test_filters.py

Add the multiple text filter as required at #151, `Multiple text filter (aiogram_ru#73126)`.
The following patterns are applied for comparison methods: 
- equals - **True** if **any** of strings in the list is equal to the text
- contains - **True** if the text contains **all** strings from the list. Reason: There is no way to do such comparison right now (except using custom filters), while the condition "if the text contains any string" can be implemented with a bunch of `register_message_handler`
- startswith - **True** if text starts with **any** string from the list. Reason: There is no need to implement "if text starts with all strings from the list" as all prefixes can be mixed in one 
- endswith - **True** if text ends with **any** string from the list. Reason: There is no need to …

Add multiple text filter

---

aiogram/utils/executor.py

Add a `relax` argument in `executor.start_polling` as stated in #183. Closes #183

Add relax argument in executor.start_polling

---

aiogram/dispatcher/dispatcher.py

Fix the values of stack levels in 3 methods in the Dispatcher. 
Here is before: ![](https://i.ibb.co/g7ds9d9/before.png)
And this is after: ![](https://i.ibb.co/Y2rRKgF/after.png)
Used listing is [here](https://gist.github.com/Birdi7/61190b0543fa9e4d590cc811ea35a800)
The output points to the actual line where the function was invoked with the deprecated argument, so it will be easier to debug.
Also, I replaced the positional arguments to kwargs

Fix stacklevel arguments in renamed arguments in the dispatcher

---

aiogram/contrib/middlewares/i18n.py

It fixes the issue when different invocations of the same `LazyProxy` object generated by `lazy_gettext("some_msg")` results in different text for different locales, as when `enable_cache=True`, the first text will be cached in the state of the object, so it will be returned on every next invocation. The behavior isn't intuitive and can be considered as a bug.
Here is the links which provide more information: [1](https://t.me/aiogram_ru/93639), [2](https://t.me/aiogram_ru/93656)

Lazy_gettext in i18nMiddleware have enable_cache=False by default

---

aiogram/utils/mixins.py

enable use syntax 'key in Obj' for objects who inherits from DataMixin
Fixes #233 
* Operating System: darwin, ubuntu

enable syntax 'key in dispatcher', issue #233

---

docs/source/migration_1_to_2.rst

As seed in [ChatMember](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/chat_member.py#L36) description, there's no `is_admin()` function, but `is_chat_admin()`.
Tried once, worked for me

Replaced is_admin() with is_chat_admin() in filters example

---

README.md

With `organization` and `svg`:
- too small size image
- wrong link
_____________
With `organization` and `png`:
- too long size image
- wrong link
_____________
With `organizations` and `svg`:
- too small size image
_____________
With `organizations` and `png`:
- too long size image
https://github.com/opencollective/opencollective/issues/2668
https://github.com/opencollective/opencollective/issues/2669

Fixed opencollective organization link

---

aiogram/dispatcher/filters/builtin.py
aiogram/utils/deep_linking.py
docs/source/utils/deep_linking.rst
tests/test_filters.py
tests/test_utils/test_deep_linking.py

Telegram bots have a deep linking mechanism, that allows for passing additional parameters to the bot on startup. It could be a command that launches the bot — or an auth token to connect the user's Telegram account to their account on some external service.
You can read detailed description in the source:
https://core.telegram.org/bots#deep-linking
We have add some utils to get deep links more handy.
Basic link example:
```python 
from aiogram.utils.deep_linking import get_start_link
link = await get_start_link('foo')  # result: 'https://t.me/MyBot?start=foo'
```
Encoded link example:
```python 
from aiogram.utils.deep_linking import get_start_link, decode_payload
link = await get_start_link('foo', encode=True)  # result: 'https://t.me/MyBot?start=Zm9v'
payload = decode_payload('Zm9v') …
```

#238 Deep linking feature

---

aiogram/bot/base.py

Looks like the latest version of aiohttp_socks available from pip did some refactoring. I tested with version 0.3.3 of aiohttp_socks
Test scrip is available [here](https://gist.github.com/a6a3uh/e6766df96cb62c873ca4062a13062d36)
* Operating System: Linux

Latest version of aiohttp_socks changed interface

---

aiogram/utils/deprecated.py

Fix the error in the decorator. In theory, a lot of existing library code is affected by this bug. Also, I removed hidden mutation of input in _handling function. Here are the my explanations of the solution for the bug: https://t.me/aiogram_ru/139903

fix: renamed_argument decorator error

---

aiogram/dispatcher/filters/builtin.py

Bug fix when CommansStart filter does not work on /start.

Fix CommandStart filter

---

aiogram/utils/callback_data.py

The Telegram Bot API documentation says that callback_data is of type String and has a size of 1-64 bytes. Therefore, in my opinion, it will be more correct to translate the resulting data into bytes, rather than counting the length of the string.
Such data will be verified:
```
from aiogram.utils.callback_data import CallbackData
cb_factory = CallbackData("pref", "name")
cb = cb_factory.new(name="абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
```
Although this should not be:
```
>>> len(cb)
38
>>> len(cb.encode())
71
```

Data validity condition changed

---

.gitignore
aiogram/contrib/fsm_storage/redis.py
tests/conftest.py
tests/contrib/fsm_storage/test_redis.py

Don't remove reference to the pool in the `close()` method and when new connection is made simply check if old one is closed.
These changes will fix the problem with pending redis pool closing tasks.
close #275 
Bug fix (non-breaking change which fixes an issue)
Described in #275

fix redis pool connection closing

---

aiogram/types/message.py

Fixed error: sending `PollOption` instead of `str`
By sending poll

fix: send_copy for poll: missed attribute getting

---

aiogram/bot/bot.py
aiogram/dispatcher/webhook.py

I had a problem with send_invoice method - looks like two parameters was missing. I found them in telegram core api, so I had to add them by myself. Also these two parameters are required for Yandex.kassa integration.
Use method 
`send_invoice(send_email_to_provider=True, send_phone_number_to_provider=True)
`
* Operating System: OS X 10.14.6
* Python version: 3.8.0

Add params send_phone_number_to_provider and send_email_to_provider

---

aiogram/types/chat.py
aiogram/types/message.py

Support links for non-public chats from this update:
https://telegram.org/blog/archive-and-new-design#easier-forwarding-links-to-messages-online-badges
For example: `https://t.me/c/1122334455/1`
Via package tests

Private chat links

---

aiogram/bot/bot.py

Supported the new darts animation for the dice mini-game in Bot API 4.8
```await bot.send_dice(message.chat.id, emoji='🎯')```
* Python version: 3.8.2

Add emoji to send_dice method

---

aiogram/utils/markdown.py
aiogram/utils/text_decorations.py
poetry.lock
tests/test_utils/test_text_decorations.py

- Updated text decorations
- Fixed mention generation with nested entities <b>@username</b>
- Fixed emoji offset

Update text decorations. Fix 'mention' generator and emoji offsets.

---

aiogram/utils/text_decorations.py
tests/test_utils/test_text_decorations.py

Fix phone_number and bot_command entity types generation

Fix phone_number and bot_command entity types generation

---

aiogram/utils/markdown.py

Markdown formatting functions use HTML escaping that causes unexpected behavior.

Fix escaping issues in markdown.py

---

aiogram/bot/base.py
tests/test_bot/test_session.py

implement "lazy" session property getter and new get_new_session for BaseBot
Fixes #314 #305 
```python
if __name__ == '__main__':
import asyncio
async def main():
from aiogram.bot.bot import Bot
bot = Bot(">.<")
await bot.send_message(124191486, "sup!")
await bot.close()
await bot.send_message(124191486, "sup! 2")
await bot.close()
asyncio.run(main())
```

fix(BaseBot): remove __del__ method from BaseBot

---

aiogram/__init__.py

Raise an `ImportError` when the user tries to use `aiogram` on Python version <3.7
```
~/vendor/aiogram> docker run -it --rm -v "$PWD/aiogram:/app/aiogram" python:3.6-slim /bin/bash
root@09f76f31ae9f:/# cd app
root@09f76f31ae9f:/app# cp aiogram/tmpbot.py ./
root@09f76f31ae9f:/app# python tmpbot.py 
Traceback (most recent call last):
File "tmpbot.py", line 1, in <module>
from aiogram import Bot, Dispatcher, types, executor
File "/app/aiogram/__init__.py", line 4, in <module>
'Python 3.7+'.format('.'.join(map(str, sys.version_info[:3]))))
ImportError: Your Python version 3.6.10 is not supported by aiogram, please install Python 3.7+
```
* Operating System: Debian buster (inside Docker)
* Python version: 3.6.10

Check whether Python is 3.7+

---

aiogram/types/inline_query_result.py

Object `InlineQueryResultPhoto` did not have field `parse_mode` while it is present in the api object description (https://core.telegram.org/bots/api#inlinequeryresultphoto).
Manually
* Operating System: Ubuntu 20.04
* Python version: 3.8.2

Fix missing InlineQueryResultPhoto parse_mode field

---

aiogram/__init__.py
aiogram/dispatcher/dispatcher.py
aiogram/dispatcher/router.py
docs/dispatcher/class_based_handlers/callback_query.md
docs/dispatcher/class_based_handlers/chosen_inline_result.md
docs/dispatcher/class_based_handlers/error.md
docs/dispatcher/class_based_handlers/inline_query.md
docs/dispatcher/class_based_handlers/message.md
docs/dispatcher/class_based_handlers/poll.md
docs/dispatcher/class_based_handlers/pre_checkout_query.md
docs/dispatcher/class_based_handlers/shipping_query.md
docs/dispatcher/dispatcher.md
docs/dispatcher/filters/command.md
docs/dispatcher/filters/index.md
docs/dispatcher/router.md
docs/index.md
poetry.lock
pyproject.toml
tests/deprecated.py
tests/test_api/test_types/test_reply_keyboard_remove.py
tests/test_dispatcher/test_deprecated.py
tests/test_dispatcher/test_dispatcher.py
tests/test_dispatcher/test_event/test_observer.py
tests/test_dispatcher/test_router.py

Rename observers but with backward compatibility, relevant documentation
The reason I didn't use `aiogram.utils.deprecated::deprecated` is I didn't want to pollute property's lower decorator and make codebase "nasty" :-)
Deprecated properties are generated with pattern. Documentation/tests was checked by me. New test to check if function is deprecated or removed in older/newer versions was added too.

AIOG-T-25 refactor(handler): rename observers

---

dev_requirements.txt

pytest-asyncio>=0.11 depends on Pytest 5.4.0 and up (details here https://github.com/pytest-dev/pytest-asyncio/pull/142), but requirements.txt states 
`pytest>=4.4.1,<4.6`
That is why `make test` failing after clonning.
Steps to reproduce:
```
git clone git@github.com:aiogram/aiogram.git temp_dir123
cd temp_dir123
python3.7 -m venv venv
. venv/bin/activate
pip install -r dev_requirements.txt
make test
```
This small fix solved it for me.
Manually
* Operating System: Ubuntu 18.04
* Python version: Python 3.7.5

fix: pytest-asyncio version conflict

---

aiogram/dispatcher/filters/builtin.py
tests/test_dispatcher/test_filters/test_builtin.py

If you pass a single string as ID (either user_id or chat_id) to IDFilter/AdminFilter - it will be treated as Iterable, as a result:
- if it is a group chat id (start with `-`) - error will be raised, since `-` can't be converted to `int`
- if it is a user_id or a personal chat (positive integer) - ID filter will not work, since string will be splitted into characters
`self.user_id` and `self.chat_id` are now `Set[int]`, since there's no point to allow passing non-unique IDs and order does not really matter.
**Examples:**
`IDFilter('-1234')` -> `ValueError: invalid literal for int() with base 10: '-'`
`IDFilter('1234')` -> filter will search for users/chats with ids `[1, 2, 3, 4]`
```python
@dp.message_handler(IDFilter('-64856280'))
@dp.message_handler(IDFilter('64856280')) …
```

Fix behavior when a single string is passed as ID

---

aiogram/types/reply_keyboard.py
tests/types/dataset.py
tests/types/test_reply_keyboard.py

Fixes #343 
The KeyboardButton object couldn't be deserialized because of no support of `conf` parameter(which is inherited from TelegramObject) in `__init__` method
Code snippet which produces the error:
```python3
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
markup = ReplyKeyboardMarkup(row_width=4, resize_keyboard=True)
markup.add(KeyboardButton('something here'))
dict_kb = markup.to_python()
assert ReplyKeyboardMarkup.to_object(dict_kb) == markup
```
- Bug fix (non-breaking change which fixes an issue)
I ran code snippet, which I included above. In addition, I added several unit tests to verify this behavior.

fix: add support init fields from parent object in KeyboardButton

---

aiogram/types/message.py

The reason is that .partition() doesn't have a default param as .split has, and default split param gives possibility to split not only by whitespaces, but also whitespace consequences (so the .strip() in get_args() not needed) and newlines.
It's called "fix", because without it, commands like this:
'''/command
arg
arg1'''
are resulting with ('/command\narg\narg1', '', '')
arg
arg1'''.partition(' '))
arg
arg1'''.split(maxsplit=1))
* Python version: 3.6.9
- [1] My code follows the style guidelines of this project
- [1] I …

fix get_full_command

---

aiogram/types/message.py

Fixes #351
command, args = cmd_args.pop(0), cmd_args.pop(0) if cmd_args else ''
* Operating System: Linux Mint 19.3
* Python version: 3.8.0

Fix message.get_full_command()

---

aiogram/types/fields.py

Fixes #307 
the functools.lru_cache() that used in `types.message.py` will affect the test. the result in #307 will be increase. if u want to test, better to set the maxsize of lru_cache to be a small number.
1.to be test more convenient.  set maxsize=1 of the lru_cache in types.message.py
2.using the code mention by #307 to test. the result will not increase for several times comunicating to the bot.  (times > the maxsize)
* Operating System: Linux-4.15
* Python version: 3.7.6

fix the #307

---

aiogram/dispatcher/dispatcher.py

If we try to get the current update from context, we get `None`:
``` python3
from aiogram import Bot, Dispatcher, executor
from aiogram.types import Message
bot = Bot("...")
dispatcher = Dispatcher(bot)
@dispatcher.message_handler()
async def handle_message(message):
current_message = Message.get_current()
print(current_message)  # None
executor.start_polling(dispatcher)
```
After the changes presented in PR, we get the current update without errors:
``` python3
@dispatcher.message_handler()
async def handle_message(message):
current_message = Message.get_current()
print(current_message)  # {"message_id": 1206, "from": {"id": 650535775, ...
print(message is current_message)  # True
```

Add setting current context of types

---

aiogram/dispatcher/dispatcher.py
aiogram/dispatcher/filters/factory.py

PR adds public registration methods for filters and middlewares so that in addition to these methods:
``` python3
dispatcher.filters_factory.bind(SomeFilter)
dispatcher.filters_factory.unbind(SomeFilter)
dispatcher.middleware.setup(SomeMiddleware())
```
...there were these:
``` python3
dispatcher.bind_filter(SomeFilter)
dispatcher.unbind_filter(SomeFilter)
dispatcher.setup_middleware(SomeMiddleware())
```

Add methods to register filters and middlewares

---

aiogram/bot/bot.py
aiogram/types/message.py

Seems field `thumb` have already been implemented in aiogram (for [send_audio](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/bot/bot.py#L299), send_document, send_video, send_animation and send_video_note)
But `thumb` parameters are only added for reply_animation/answer_animation, this commit add these missing `thumb` parameters for them.
Also updated document, the [Telegram Bot API document](https://core.telegram.org/bots/api#sendaudio) says the thumbnail should not exceed 320x320 now.
> The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320.
Fixes #357 
I didn't test all of them, only tried to add thumb parameter for `reply_audio` and I can successfully send audio with thumbnails.
**I'm still very new to python …

Add missing thumb parameter

---

aiogram/dispatcher/filters/builtin.py
tests/test_dispatcher/test_filters/test_builtin.py
tests/types/dataset.py

IDFilter checks correctly message from channel. For previous behaviour, check the corresponding issue
Fixes #375
Unit-test was added

fix: bug IDFilter checking message from channel

---

aiogram/bot/bot.py
aiogram/types/message.py

Add missed answer_poll and reply_poll methods to Message
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
On own bot with `pip install -e`

Add missed answer_poll and reply_poll methods to Message

---

aiogram/bot/bot.py

``` python3
import asyncio
from aiogram import Bot
from aiogram.types import InputFile
BOT_TOKEN = "..."
CHAT_ID = ...
async def main():
bot = Bot(token=BOT_TOKEN)
await bot.send_document(chat_id=CHAT_ID,
document=InputFile("document.zip"),
thumb=InputFile("thumb.jpg"))
await bot.close()
asyncio.run(main())
```
Fixes #389

Fix showing thumb when sending document (#389)

---

aiogram/utils/text_decorations.py

html.escape replaces " and ' characters by default which is **NOT** required by Telegram and causes unexpected behavior with single quotes. `quote=False` argument fixes that.

Fix HTML characters escaping

---

aiogram/utils/text_decorations.py
tests/test_utils/test_text_decorations.py

Fix #413 parse entities positioning

---

aiogram/contrib/middlewares/i18n.py
examples/i18n_example.py

1. Replaced one file translation to all project folder translation. It's more usable case. 
2. `For e.g.` --> `E.g.`. E.g. is short for `exempli gratia` which means simply `for example`. So if you write `for e.g.`, you are in effect writing `for for example`. 
3. `xargs` replased with serveral lines, `xargs` is not appliable for Microsoft Windows users. 
4. Added info about translation tools and `.po` files location.
5. Minor typo edits.

I18n example patch (added docs and fixed typos)

---

docs/source/quick_start.rst

Quick Start documentation example has invalid code blocks. Fixed it.
Not tested

Fixed docs Quick start page code blocks

---

aiogram/types/update.py
aiogram/utils/deprecated.py
tests/test_utils/test_deprecated.py

hotfix(updates): CHOSEN_INLINE_RESULT is a correct API-term

---

examples/callback_data_factory.py
examples/callback_data_factory_simple.py

fixed type hints
its impotant to remeber all data saved in callback_data is text even if you pass to it integer
insofar as newbies often copy examples and modyfy this typing may help them make no mistake
* Operating System: Windows 10 x64
* Python version: 3.8.5

fixed type hints of callback_data

---

aiogram/bot/api.py
aiogram/bot/bot.py
aiogram/types/chat_member.py
aiogram/types/input_media.py

Add is_chat_creator method to ChatMemberStatus

---

aiogram/types/message.py

Only `forward_date` is required to be in forwarded message (https://core.telegram.org/bots/api#message).
But code like
```python3
if message.forward_date:
return True
```
looks ambigous, so I added this method 
```python3
if message.is_forward():
return True
```
Also I added some return types at nearest code.
On my bot.

Add is_forward method to Message

---

aiogram/bot/base.py
aiogram/dispatcher/dispatcher.py
aiogram/dispatcher/middlewares.py

on ::Bot, ::Dispatcher initializators
Fixes #365
The following should work
```python3
from aiogram import Bot, Dispatcher, types
bot = Bot(TOKEN)
dp = Dispatcher(bot=bot)
@dp.message_handler()
async def echo_processor(event: types.Message):
await event.reply(event.html_text, parse_mode=types.ParseMode.HTML)
async def main():
await bot.send_message(CHAT_ID, "Hi!")
try:
await dp.start_polling()
finally:
await bot.close()
await dp.wait_closed()
if __name__ == '__main__':
import asyncio
asyncio.run(main())
```

fix(bot,dispatcher): do not use _MainThread event loop

---

aiogram/contrib/middlewares/environment.py
aiogram/dispatcher/webhook.py
aiogram/utils/executor.py

property DP.loop may be None, executor and webhook view should both respect that

hotfix(dispatcher): when DP.loop None

---

aiogram/types/message.py

Added disable_web_page_preview for `Message.send_copy(...)` in case of text messages.
Other content types will ingore this param.
Fixes #429 

#429 added disable_web_page_preview for Message.send_copy(...)

---

aiogram/dispatcher/event/handler.py
tests/test_dispatcher/test_handler/test_base.py

Unwraps the callback before awaitable check
Fixes #434 

HandlerObject: Unwrap handler before awaitable check

---

aiogram/utils/exceptions.py

Actual message after bot kicked:
`Forbidden: bot was kicked from the supergroup chat`

Fixed BotKicked match text

---

aiogram/types/chat.py

Added SUPERGROUP chat type, because SUPER_GROUP is incorrect and confusing.
Even [Telegram API](https://core.telegram.org/api/channel) calls this type of chats "supergroups" and not "super groups", so using underscore if needless.
Added ChatType.SUPERGROUP, which may replace SUPER_GROUP in future. For now, both types will present.
Fixes #356 
No tests except one manual test case:
```python
@dp.message_handler(chat_type=[types.ChatType.SUPERGROUP])
async def get_data(message: types.Message):
await message.answer("Oh, hi, Mark!")
```
You can still use `SUPER_GROUP`, but it will raise DeprecationWarning.
This works fine on my local setup
* Python version: 3.8.5

Added SUPERGROUP chat type

---

aiogram/types/chat.py

The parameter `is_anonymous` exists in the full promoteChatMember method but is missing from its shortcut.
* Operating System: Ubuntu 20.04

Add a missing parameter to promoteChatMember shortcut

---

aiogram/types/message.py

Added missing parameter in ```types.message.reply_video``` function and removed redundant ```chat_id``` docstrings
* Operating System: Windows 10 20H2
* Python version: 3.8.2

Add parameter supports_streaming to reply_video

---

aiogram/bot/bot.py

when entities are set, default parse_mode become disabled
Fixes #460 

when entities are set, default parse_mode become disabled

---

aiogram/types/message.py

send_video and reply_video have `support_streaming` argument while `answer_video` does not. This PR fixes it.

Added missing "supports_streaming" argument to answer_video method

---

aiogram/types/input_media.py

Uncommented `attach_document` and `attach_audio` MediaGroup methods
Fixes #467

#467 Uncommented `attach_document` and `attach_audio` MediaGroup methods

---

aiogram/api/client/session/aiohttp.py
tests/test_api/test_client/test_session/test_aiohttp_session.py

check if value is `UNSET` while building http request.

fix(aiohttp-session): respect UNSET sentinel

---

aiogram/types/message.py

Added the ability to pass more parameters (`kwargs`) from methods `Message().answer_location()` and `Message().reply_location()` to `self.bot.send_location()`
No tests run. I believe it's a small change and it doesn't break anything.

Add ability to `.answer_*` and `.reply_*` live location

---

aiogram/dispatcher/dispatcher.py

in Dispatcher check_key and release_key functions
(need User.id for future use, not User object)
there was a bug in check_key and release_key functions.
When we call these functions with no chat_id or user_id argument, they cannot set user_id and chat id variable correctly, becouse this code:
user_id = types.User.get_current()
chat_id = types.Chat.get_current()
return User/Chat object, not user/chat id
* Operating System: Windows 10 | Linux Manjaro
* Python version: 3.7.10 |  3.9.2

fix bug in getting user_id, chat_id from context

---

aiogram/types/input_media.py

The methods of MediaGroup were missing some parameters, type hints and docstrings. This PR fixes that along with all the mess.

Fix types.MediaGroup methods

---

aiogram/types/chat_member_updated.py

This fixes `TypeError: Value should be instance of 'User' not 'NoneType'`
Related: https://t.me/aiogram_ru/489310
Desperate Times Call for Desperate Measures, so no tests, except running bot once. You can test it yourself by blocking and unblocking your bot.
* Operating System: Manjaro
* Python version: 3.9

Added alias to from_user field, fixed TypeError

---

aiogram/types/base.py

Removed 'raise KeyError(key)'
Fix error:
```
File "/usr/local/lib/python3.8/dist-packages/aiogram/types/chat.py", line 112, in get_url
await self.update_chat()
File "/usr/local/lib/python3.8/dist-packages/aiogram/types/chat.py", line 124, in update_chat
self[key] = value
File "/usr/local/lib/python3.8/dist-packages/aiogram/types/base.py", line 228, in __setitem__
raise KeyError(key)
KeyError: 'message_auto_delete_time'
```
* Operating System: Windows 10, Ubuntu 20.04.2 LTS
* Python version: 3.8.5, 3.8.7

FIX TelegramObject.__setitem__

---

aiogram/types/message.py

Property types.Message.url uses deprecated method 'is_private' when checks chat type. I've replaced it
Fixes #552 
Operating System: Win10
Python version: 3.9.2

Replace deprecated 'is_private' method

---

aiogram/dispatcher/webhook.py
aiogram/types/message.py

The documented media caption limits were updated to the current limits as per https://core.telegram.org/bots/api

Update documented caption limits to the current limit.

---

aiogram/bot/bot.py

Bot.create_chat_invite_link()
Bot.edit_chat_invite_link()
Bot.revoke_chat_invite_link()
need to return types.ChatInviteLink, not dict
Fixes #548
Maybe this fix be breaking if users use dicts that was returned by these methods
* Python version: 3.9.2

Fix `Bot.*_chat_invite_link` not returning `ChatInviteLink` (#548)

---

aiogram/dispatcher/filters/builtin.py

Fixes #556 
* Python version: 3.8.1

fix: builtin command filter args (#556)

---

aiogram/types/message.py

```python
@dispatcher.message_handler(commands=["command"], commands_ignore_caption=False, content_types=types.ContentType.ANY)
async def message_handler(message: types.Message):
print( message.get_full_command() )    
```

fix get_full_command for messages with caption

---

aiogram/utils/text_decorations.py

This fix adds `'\n'` symbols at begin and end of inserted text to `pre()` formatter in Makdown(V2) style as it described in [official documentation](https://core.telegram.org/bots/api#formatting-options).
Fixes #596 
Fixes #481 

fix for text decoration pre() bug

---

aiogram/types/input_media.py

Add `caption_entities` field in `InputMedia` base class.
Fixes #575

Add caption_entities in InputMedia base class

---

aiogram/utils/exceptions.py

GroupDeactivated exception text was changed to `BadRequest: Group chat was deactivated`.
- [] I have added tests that prove my fix is effective or that my feature works

GroupDeactivated exception text update

---

aiogram/types/message.py

Fixed syntax bug, added comma
Just added a comma, the absence of which the interpreter did not take as a syntax error

Fix syntax bug in message.py

---

aiogram/bot/api.py
aiogram/bot/bot.py
aiogram/types/chat.py
tests/test_bot.py

Add required changes to cover API 5.3.

refactor: renamed getChatMembersCount to getChatMemberCount

---

README.md
README.rst
aiogram/__init__.py
aiogram/bot/api.py
aiogram/bot/bot.py
aiogram/types/__init__.py
aiogram/types/bot_command_scope.py
aiogram/types/chat.py
aiogram/types/chat_member.py
aiogram/types/force_reply.py
aiogram/types/reply_keyboard.py
docs/source/index.rst
tests/test_bot.py
tests/types/test_chat_member.py

Telegram API 5.3

---

.gitignore
aiogram/dispatcher/dispatcher.py
aiogram/utils/handlers_in_use.py
examples/specify_updates.py
tests/test_dispatcher/test_dispatcher.py

In new version of aiogram we can't specify which updates from telegram we need to receive. this PR resolve problem
I wrote simple example with nested routers which uses different types of updates
* Operating System: Windows 10/Ubuntu CodeSpaces
* Python version: 3.8.6 64x

Added ability to specify which update bot need to receive and process while using polling mode

---

aiogram/dispatcher/event/handler.py
tests/test_dispatcher/test_event/test_handler.py

Fix not all args are passed to handler function invocation. Handlers wrapped with `functools.partial` or having keyword-only arguments won't work without this:
```python
...
async def sender(event: Message, command: Union[CommandObject, str], categories: list[str]):
print(locals())
dp.message.register(sender, commands=['foo', 'bar'])
dp.message.register(functools.partial(sender, command='foo'))
...
```
```python
ERROR:aiogram.dispatcher:Cause exception while process update id=xxx by bot id=xxx
TypeError: sender() missing 1 required positional argument: 'categories'
Traceback (most recent call last):
File "<project-dir>/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 279, in _process_update
response = await self.feed_update(bot, update, **kwargs)
File …
```

Fix not all args are passed to handler function invocation.

---

aiogram/bot/bot.py

Fix between condition in send_media_group method

Fix between condition in send_media_group method

---

aiogram/bot/bot.py
aiogram/types/chat.py
aiogram/types/chat_member.py
aiogram/types/fields.py
tests/test_bot.py
tests/types/dataset.py

`ChatMemberOwner` and `ChatMemberAdministrator` now have similar fields to improve compatibility and simplify checks.
On my bot, which often deal with promotions.
Also, I added a new test case.

Add to ChatMemberOwner new default fields

---

aiogram/utils/callback_data.py
tests/test_utils/test_callback_data.py

- Allow to use `CallbackData` with zero parts, next code was raising `TypeError`:
```python3
cb = CallbackData('zero')
```
- Allow to parts to be empty, next code was raising `ValueError`:
```python3
cb = CallbackData('simple', 'action')
cb.new('')
```
I added three new tests to cover main usages of `CallbackData`
* Python version: Python 3.8

Allow empty and zero parts in CallbackData

---

aiogram/dispatcher/fsm/state.py
tests/test_dispatcher/test_fsm/test_state.py

Added filtering by StatesGroups
There is also a [second](https://github.com/darksidecat/aiogram/commit/0e5285701226cea9d5ba1340d8410d6dcf2693f2) filtering implementation
Usage:
```python3
router.message.filter(StatesGroupName())
```
* Python version: 3.9.1

Add StatesGroup filter

---

CHANGES/662.feature
aiogram/types/message.py
tests/test_api/test_types/test_message.py

add aliases for edit/delete reply markup to Message
* Python version: 3.9.2

add aliases for edit/delete reply markup to Message

---

aiogram/contrib/fsm_storage/redis.py
tests/conftest.py
tests/contrib/fsm_storage/test_storage.py

Forget to add `async` for Redis .close() coro.
Thanks @darksidecat for comment https://github.com/aiogram/aiogram/pull/649#pullrequestreview-741587542
By the way fixed some bugs and fixed tests.
- adapter redis init
- await close
- string typing (to prevent aioredis compatibility issues)
- skip tests for RedisStorage v1 with aioredis v2
- fixed lazy fixture issue
- fixed connection pool test issue
Sorry for large PR, but only merge of all of this issue fixes make able to test redis support correctly.

RedisStorage major fixes + tests updates

---

aiogram/contrib/middlewares/logging.py

Now LoggingMiddleware doesn't show CallbackQuery.data.
This PR will fix it :) 

Show callback_query.data in logging

---

aiogram/bot/bot.py

Media groups work well even with 1 media element inside. So this check unnecessarily strict.
The check was fixed in https://github.com/aiogram/aiogram/pull/642, it's working now, but it's bad 😅
On my bot with many media groups.
* Operating System: macOS
* Python version: 3.9.6

enh: remove unnecessarily strict condition in send_media_group

---

aiogram/utils/markdown.py

There is a problem with the current symbol on android devices. When trying to change the text of a post in a channel, the hidden link often disappeared when editing. Word joiner symbol seems to be more stable in this case.
https://en.wikipedia.org/wiki/Word_joiner
On my bot. Unfortunately it's impossible to test without Telegram servers and User API.
* Operating System: macOS / Android
* Python version: 3.9
https://user-images.githubusercontent.com/6163085/140058026-4e78b79e-4050-4651-acd2-688517856fbf.mp4

enh: change invisible symbol in hide_link

---

aiogram/bot/base.py
aiogram/bot/bot.py
aiogram/types/mixins.py
tests/test_bot/test_bot_download_file.py

* add the ability to save files to a directory with path completion based on `file.file_path`,
* add an option to automatically create directories in the file path
* Operating System: Win 10
* Python version: 3.9.6

add `Bot.download_file` aliases ability to save files to a directory and automatically create directories

---

CHANGES/759.feature
aiogram/__init__.py
aiogram/utils/magic_filter.py
docs/dispatcher/filters/magic_filters.rst
poetry.lock
pyproject.toml
tests/test_utils/test_magic_filter.py

Added possibility to get MagicFilter result as handler argument
```python
from aiogram import F
...
@router.message(F.text.regexp(r"^(\d+)$").as_("digits"))
async def any_digits_handler(message: Message, digits: Match[str]):
await message.answer(html.quote(str(digits)))
```

Extended MagicFilter with aiogram-specific operation

---

CHANGES/751.bugfix
aiogram/dispatcher/handler/__init__.py

The ChatMemberUpdated class is being imported instead of ChatMemberHandler, which is wrong here.

Fix ChatMemberHandler import in __init__.py

---

docs/utils/i18n.rst

https://github.com/aiogram/aiogram/blob/24a805d517edd3618371fa401b08d3fe8b58e676/aiogram/utils/i18n/core.py#L12-L19

Typo fix in docs: language -> default_locale

---

CHANGES/785.feature
aiogram/dispatcher/webhook/aiohttp_server.py

Added possibility to pass additional arguments into the aiohttp webhook handler to use this
arguments inside handlers as the same as it possible in polling mode.
Fixes #785

Added possibility to pass kwargs into handlers from webhook

---

aiogram/types/base.py

Object representation in pydantic style is very handy on debugging. E.g. with Sentry:
As you can see, Item (pydantic object) shows it's fields.
So it would be nice to see Telegram Objects this way in aiogram 2.x
```python
import logging
from aiogram import Bot, Dispatcher, executor
from aiogram.types import Message
logging.basicConfig(level=logging.INFO)
bot = Bot(token='TOKEN')
dp = Dispatcher(bot)
messages = []
@dp.message_handler()
async def echo_handler(message: Message):
messages.append(message)
logging.info("Collected messages: %s", messages)
await message.answer(message.text)
if __name__ == '__main__':
executor.start_polling(dp, skip_updates=True)
```
BEFORE:
```
INFO:root:Collected messages: [<aiogram.types.message.Message object at 0x101d94c40>]
```
AFTER:
```
INFO:root:Collected …
```

Add TelegramObject readable representation

---

CHANGES/791.bugfix
aiogram/dispatcher/filters/state.py
tests/test_dispatcher/test_filters/test_state.py

At the moment of preparing this PR, the StateFilter, given a sequence of values, makes a check only for its first element, which results in unexpected behavior for developers using the framework.
* Operating System: Windows 11
* Python version:  3.9.6

Fix unexpected behavior of sequences in StateFilter

---

aiogram/dispatcher/dispatcher.py

Remove `Optional` where default argument is not None.
At first I planned this PR to be about replacing `run_task=None` by `run_task=False`, but it turns out it is different things in this context.

Remove unnecessary `Optional`s

---

docs/dispatcher/router.rst

Obvious grammar errors have been corrected. Use free services like grammarly.com to check your spelling.

Correct grammar errors

---

docs/dispatcher/filters/index.rst

Replace `from aiogram.filters import BaseFilter` with `from aiogram.dispatcher.filters import BaseFilter`
Fixes #753

Typo fix in docs: invalid import

---

aiogram/dispatcher/dispatcher.py
aiogram/types/update.py

Deleting deprecated `CHOSEN_INLINE_QUERY`
Removing outdated code
Fixes #589 
* Operating System: Windows 7
* Python version: version: 3.8.10

Deleting deprecated CHOSEN_INLINE_QUERY

---

aiogram/types/base.py
tests/conftest.py
tests/test_bot.py
tests/test_dispatcher.py
tests/test_message.py
tests/types/dataset.py
tests/types/test_chat.py

Fixes #513
Set value similar to `__init__`, default parent is self:
https://github.com/aiogram/aiogram/blob/4d2d81138681d730270819579f22b3a0001c43a5/aiogram/types/base.py#L95
PyTest [100%] PASSED 
`.update_chat()` 100% covered

Fix: default parent for `__setitem__`

---

CHANGES/827.bugfix
aiogram/dispatcher/filters/exception.py
tests/test_dispatcher/test_filters/test_exception.py

Fix exception filters
Exception filters `__call__` first parameter must be event from Telegram
Fixes #822 
* Operating System: Manjaro 21.2.2 Qonos
* Python version: Python 3.10.1

Fix: close #822 Fix exception filter

---

aiogram/contrib/fsm_storage/mongo.py

Added the passing of `self._kwargs` received in `MongoStorage`'s init to `AsyncIOMotorClient` when it is initialized.
This is needed to enable SSL and many other things.
`AsyncIOMotorClient` inherits all of the options from `pymongo`'s `MongoClient`, which has a practically endless list of them: https://pymongo.readthedocs.io/en/3.12.0/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient
Supporting all of them explicitly isn't really an option, so what we can do is just pass down all of the user's custom kwargs to the client.
Otherwise one has to subclass `MongoStorage` and redefine `get_client` completely.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …

Add support for custom kwargs for AsyncIOMotorClient in MongoStorage

---

aiogram/dispatcher/dispatcher.py

Changed skip updates method from using `get_updates `with `offset=-1` to `delete_webhook` with `drop_pending_updates=true`
Fixes #418

Changed skip updates method

---

docs/utils/i18n.rst

The I18n Class gets imported in 3.0.0b2 as follows:
```python
from aiogram.utils.i18n import I18n
```
Whereas the documentation implies that it should be:
```python
from aiogram.utils.i18n.code import I18n
```
* Operating System: Linux
* Python version: 3.10.4
* aiogram version: 3.0.0b2

Fixed path of I18n Class

---

aiogram/types/fields.py

Fixes #349 
```
@dp.chat_join_request_handler()
async def chat_join_request_handler(chat_join_request: types.ChatJoinRequest) ->None:
print(chat_join_request)
```
* Operating System: Windows 10 Pro 21H1 (19043.1586)
* Python version: Python 3.10.4 (tags/v3.10.4:9d38120) [MSC v.1929 64 bit (AMD64)]

Fix datetime serialization error on Windows

---

aiogram/dispatcher/dispatcher.py

`del bucket['key']` -> `del bucket[key]`
Fixes #907
-  Bug fix (non-breaking change which fixes an issue)
- `await dispatcher.release_key('my_key')`
* Operating System: win 10
* Python version: 3.10
-  My code follows the style guidelines of this project
- I have performed a self-review of my own code
-  My changes generate no new warnings
-  New and existing unit tests pass locally with my changes

fix Dispatcher.release_key

---

CHANGES/901.bugfix.rst
aiogram/methods/base.py
aiogram/types/force_reply.py
tests/test_api/test_methods/test_send_message.py

Fixed false-positive coercing of Union types in API methods 
Fixes #901

#901 Fixed false-positive coercing of Union types in API methods 

---

CHANGES/922.feature.rst
aiogram/dispatcher/fsm/storage/redis.py

Use `float` and `datetime.timedelta` type hints in `RedisStorage.state_ttl` and `RedisStorage.data_ttl`.
Let's reuse type hint `ExpiryT` from redis.

Fix type hints for redis TTL params

---

aiogram/types/base.py

Rework warning for not defined fields in `TelegramObject.__setitem__`.
`warnings.warn` should be shown once instead of logging every warning in to the log.

Rework warning for not defined fields in `TelegramObject`

---

aiogram/dispatcher/handler.py

Fixed unregister function in dispatcher. In release version it just delete first of handlers
Message and query handlers was delete by new realisation and bot starts correctly without deleted methods.
* Operating System: Ubuntu 20.0.4
* Python version: python3.8

fix unregister handlers

---

aiogram/dispatcher/filters/builtin.py
aiogram/types/chat.py

I added the ability to work with the ChatTypeFilter filter with inline mode. Also added a new type of chat - sender, also added it to the documentation in the chat types
* Operating System:  Ubuntu 20.04 LTS
* Python version: 3.8.10

make ChatTypeFilter work with inline queries

---

README.md

This PR changes Telegram Bot API shield badge version to 6.1 _(Which was updated only in README.rst)_

Update Telegram Bot API shield badge version in README.md

---

.github/workflows/label_pr.yaml

Add GitHub Actions workflow to automatically put `3.x` label on new pull requests to `dev-3.x` branch.

Automatically put `3.x` label on new pull requests to `dev-3.x`

---

.github/workflows/label_pr.yaml

Add GitHub Actions workflow to automatically put `2.x` label on new pull requests to `dev-2.x` branch.

Automatically put `2.x` label on new pull requests to `dev-2.x`

---

CHANGES/944.misc.rst
aiogram/types/message_entity.py
tests/test_api/test_types/test_message_entity.py

Renamed `MessageEntity.extract` to `MessageEntity.extract_from`
Removed `MessageEntity.get_text`
Fixes #944 

#944 Rename "extract()" to "extract_from()" for entities

---

CHANGES/929.feature.rst
aiogram/types/chat.py
tests/test_api/test_types/test_chat.py

In some cases it's handy to get user's current params via `get_chat` method.
Then you want to use `full_name` shortcut similar to `User`, but it's absent for `Chat`... :(
So, may be add it? :)

Add `full_name` shortcut for `Chat`

---

.github/workflows/pull_request_changelog.yml

- Make check faster when `skip news` label is present by reducing number of steps
- Add `name:` root field to make it look better in GitHub UI
The first action doesn't have a name, the second one has.
Note that I haven't tested this

Improve changelog check action

---

.github/ISSUE_TEMPLATE/bug.yaml

Example: https://github.com/evgfilim1/actions-test/issues/7

Split "Context" textarea field inside Issue template into several required input fields

---

CHANGES/972.bugfix.rst
aiogram/dispatcher/fsm/storage/redis.py

After the event isolation was rewritten, default Redis lock kwargs, specifically timeout, were left out, causing locks to be permanent, which might result in some users being continuously ignored in case the bot is restarted during the update processing.
- Operating system: Windows 11
- Python version: 3.10.6

Fix default lock kwargs in RedisEventIsolation

---

aiogram/dispatcher/filters/builtin.py
tests/test_dispatcher/test_filters/test_builtin.py

it will be usefull for bots using SetMyCommands api call. 
Example:
```python
ABOUT_CMD = BotCommand("about", "few info about bot, its creater etc")
...
@dp.message_handler(commands=ABOUT_CMD)
async def about_cmd_handler(m: Message):
...
```
* Python version: 3.8.9
Few tests are not pass. Probably problem is in windows  ( https://t.me/aiogram_ru/1176021 )

command filter now can be sets with BotCommand object

---

aiogram/bot/base.py
aiogram/bot/bot.py
aiogram/dispatcher/webhook.py

add global default parameter protect_content for Bot.
Usage. For make all messages by bot protected by default add new keyword arg to Bot constructor:
```python 
bot = Bot(..., protect_content=True, ...)
```
I have been using this feaеure in production bot since January 2022, no problems found.

Add `protect_content` global default

---

aiogram/dispatcher/middlewares.py

Fix filtering skip_patterns

---

aiogram/dispatcher/filters/builtin.py

In current version adding `chat_id` filter to `chat_join_request_handler` leads to never-executing-handler.
This PR fixes such behavior.
```
dispatcher.register_chat_join_request_handler(
self.join_request,
chat_id=self.config["bot"]["chat_id"]
)
```
Before PR: it didn't handle any updates. After PR: it handles updates from given chat.
(sorry, I don't think I'll able to write some tests in the near future)
- Operating system: NixOS 22.05
- Python version: 3.10.1

Add IDFilter support for ChatJoinRequest events

---

CHANGES/995.misc.rst
aiogram/dispatcher/dispatcher.py

Sometime Telegram restart the server with HTTP 429 error, so that's mean we need to handle it in polling mode

Prevent to crash polling

---

CHANGES/1017.doc
docs/locale/uk_UA/LC_MESSAGES/index.po

Пофікшені і додані деякі переклади
- Documentation (translations)
🤔🤔🤔
- Operating system: 🤔
- Python version: 🤔

Fix UA translations in index.po

---

CHANGES/1029.doc.rst
aiogram/types/message.py

Fix typehints for `Message` `reply_media_group` & `answer_media_group` methods
Fix typehints to be the same as in:
- BotAPI `sendMediaGroup`: [link](https://core.telegram.org/bots/api#sendmediagroup)
- aiogram dev-3 `send_media_group`: [link](https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/client/bot.py#L1065)
- aiogram dev-3 documentation: [link](https://docs.aiogram.dev/en/dev-3.x/api/methods/send_media_group.html)
Local test run.

Fix typehints for `Message` media group methods

---

aiogram/bot/bot.py
aiogram/dispatcher/webhook.py
aiogram/types/__init__.py
aiogram/types/chat.py
aiogram/types/chat_administrator_rights.py
aiogram/types/chat_member.py
aiogram/types/chat_permissions.py
aiogram/types/forum_topic_closed.py
aiogram/types/forum_topic_created.py
aiogram/types/forum_topic_reopened.py
aiogram/types/message.py
aiogram/types/video_chat_started.py
tests/types/dataset.py
tests/types/test_chat_member.py

https://core.telegram.org/bots/api-changelog#november-5-2022
Added support for topics in 2.x
--
- Operating system: Windows 10 x64
- Python version: Python 3.10

Added support for topics in Bot API 6.3

---

aiogram/dispatcher/handler.py

Add checking for handler_obj.handler
At Handler unregister method variable registered was unused so removing handlers by handler function was did`t work. That fix add checking of handler_obj.handler.
- Bug fix
- Register handler with dp.register_message_handler(some_func) and then call dp.messages_handler.unregister(some_func)
-Python version: 3.9.1

Fix Handler unregister

---

aiogram/types/message.py

Added check for is_topic_message in answer/reply methods
--
- Operating system: Windows 10 x64
-Python version: Python 3.10

Fix for groups without topics

---

CHANGES/1060.doc.rst
aiogram/dispatcher/router.py

`include_router` method in `Router` has an old now non-working feature still documented. It was removed in #897.
- Documentation (typos, documentation)

Removed an old now non-working feature from documentation

---

aiogram/types/chat.py

Fixed a problem in the aiogram/types/chat file, the "promote" function.
Added parameters:
can_manage_chat
can_manage_video_chats
can_manage_topics

BugFix in chat.promote

---

tests/conftest.py
tests/test_bot.py
tests/test_bot/test_bot_download_file.py
tests/test_contrib/test_fsm_storage/test_storage.py
tests/test_dispatcher.py
tests/test_dispatcher/test_middlewares/test_lifetimecontroller.py
tests/test_filters.py
tests/test_message.py
tests/test_utils/test_deep_linking.py
tests/types/test_chat.py
tests/types/test_mixins.py

Made a fix to avoid asyncio marker warnings that were applied to non-asynchronous tests.
Now you do not need to put this marker in every file with asynchronous tests, as it is applied automatically.
Fix #1005
This is just a bug fix in tests, not breaking change) 
To test the fix, you can run tests and make sure there are no warnings about `pytest.mark.asyncio`.
- All tests run with the `make test` command

Fix warning about asyncio marker in tests

---

aiogram/types/chat_permissions.py

As asked by Alex: add new fields, make sure kwargs are not ignored, add a comment next to can_send_media_messages
ran a bot that uses updated ChatPermissions
- Operating system: e.g. Ubuntu 20.04.2 LTS
-Python version: e.g. 3.10.1

adapt ChatPermissions for Bot API 6.5

---

CHANGES/1114.misc.rst
aiogram/dispatcher/event/telegram.py
aiogram/exceptions.py
tests/test_dispatcher/test_event/test_telegram.py

The most common question from the newbies who migrating from 2.x version to 3.x that is `TypeError: TelegramEventObserver.__call__() got an unexpected keyword argument '<name>'`.
This error caused in due to keyword-filters is no more supported (#942).
This pull-request adds an customized error with explanation why you can't use keyword filters with link to the documentation.

Replaced error `TypeError: TelegramEventObserver.__call__() got an unexpected keyword argument '<name>'` with a more understandable

---

CHANGES/1117.feature.rst
aiogram/dispatcher/router.py
tests/test_dispatcher/test_router.py

Added a method that allows you to compactly register routers
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
Type here...
- Operating system: Windows 10
- Python version: 3.10.9

add new method for Router

---

CHANGES/1120.misc.rst
aiogram/dispatcher/dispatcher.py
aiogram/methods/base.py
aiogram/webhook/aiohttp_server.py
tests/test_dispatcher/test_dispatcher.py
tests/test_webhook/test_aiohtt_server.py

Added possibility to reply into webhook with files.
Previously there was no support for sending documents in reply into webhook because `application/json` response type is used, but Telegram Bot API supports `multipart/form-data` responses from webhook serve ([Docs](https://core.telegram.org/bots/api#making-requests-when-getting-updates)), so thats mean the sending documents is supported by server.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Added possibility to reply into webhook with files

---

CHANGES/1155.bugfix.rst
aiogram/dispatcher/dispatcher.py

I fixed bug by adding Dispatcher's workflow_data to the passed arguments of event handlers.
Webhook's signature:
https://github.com/aiogram/aiogram/blob/fea1b7b0a385e4dd701ea644fd6e9052ec95c587/aiogram/webhook/aiohttp_server.py#L28-L33
Current polling's signature:
https://github.com/aiogram/aiogram/blob/fea1b7b0a385e4dd701ea644fd6e9052ec95c587/aiogram/dispatcher/dispatcher.py#L491-L492
New polling's signature:
https://github.com/aiogram/aiogram/blob/c40c9dae67859ff50c58ec82c11fd146cfeae389/aiogram/dispatcher/dispatcher.py#L491-L497
Fixes #1155 
No additional tests were created, as there is no tests testing passed arguments. It would be great, if they will be added.

Resolve  #1155: Different signature of startup/shutdown events on polling and webhooks 

---

.butcher/enums/InlineQueryResultType.yml
CHANGES/1146.bugfix.rst
aiogram/enums/inline_query_result_type.py
aiogram/types/inline_query_result_cached_mpeg4_gif.py
aiogram/types/inline_query_result_mpeg4_gif.py

Change type of result in `InlineQueryResult` enum for `InlineQueryResultCachedMpeg4Gif]` and `InlineQueryResultMpeg4Gif` to more correct according to documentation

Change `InlineQueryResultType.MPEG` to more correct

---

docs/api/upload_file.rst

Wrong link to input_file docs page.
Also, it was changed in #1133

fix(docs): fix wrong page link in docs

---

CHANGES/1144.misc.rst
aiogram/fsm/context.py
aiogram/fsm/middleware.py
aiogram/fsm/storage/base.py
aiogram/fsm/storage/memory.py
aiogram/fsm/storage/redis.py
tests/test_fsm/storage/test_isolation.py
tests/test_fsm/storage/test_storages.py
tests/test_fsm/test_context.py
tests/test_utils/test_i18n.py

storage cleanup.
This change shouldn't affect you if you're writing bots, but if you're implementing a storage provider it might break your code.

storage cleanup

---

CHANGES/1176.bugfix.rst
aiogram/utils/text_decorations.py
tests/test_utils/test_text_decorations.py

In [telegram bot api documentation](https://core.telegram.org/bots/api#markdownv2-style) said that need two characters, but there we have only one. I did catch a bug with this, but github issue I didn't find and don't want to create.
- Bug fix (non-breaking change which fixes an issue)
I tested it on my own project, but you can use this code:
```python
...
@router.message()
async def test(m: types.Message):
return await m.answer(m.md_text)
```

Fix markdown spoiler

---

aiogram/types/message.py

…ation methods
Bot API 6.4
Added the parameter has_spoiler to the methods sendPhoto, sendVideo, and sendAnimation.

fix: add has_spoiler param 

---

CHANGES/1173.feature.rst
aiogram/webhook/aiohttp_server.py
tests/test_webhook/test_aiohtt_server.py

Added X-Telegram-Bot-Api-Secret-Token header check

parameter secret_token

---

CHANGES/1210.misc.rst
aiogram/client/context_controller.py
aiogram/client/session/aiohttp.py
aiogram/client/session/base.py
aiogram/methods/base.py
aiogram/types/base.py
aiogram/types/callback_query.py
aiogram/types/chat.py
aiogram/types/chat_join_request.py
aiogram/types/inline_query.py
aiogram/types/input_file.py
aiogram/types/message.py
aiogram/types/sticker.py
aiogram/types/user.py
tests/mocked_bot.py
tests/test_api/test_client/test_context_controller.py
tests/test_api/test_client/test_session/test_base_session.py
tests/test_api/test_methods/test_base.py
tests/test_api/test_types/test_input_file.py

Proof of concept for a replacement of ContextVar's for Bot instance inside method shortcuts
with a implementation based on a new pydantic feature named [Validation Context](https://docs.pydantic.dev/latest/usage/validators/#validation-context).
The motivation behind this pull request is to enhance the current implementation of ContextVar's for the Bot instance inside method shortcuts. The existing approach using ContextVar's can be confusing for new users and lacks clarity in its usage. By leveraging a new feature called "Validation Context" in Pydantic, we can provide a more transparent and intuitive solution.
The Validation Context feature in Pydantic offers a clearer and more explicit way of passing the Bot instance to method shortcuts. It eliminates the ambiguity associated with …

PoC: Bot instance inside method shortcuts using pydantic Validation Context

---

CHANGES/1221.misc.rst
aiogram/filters/command.py
pyproject.toml

Updated magic filter to 1.0.10
Changelog: https://github.com/aiogram/magic-filter/releases/tag/v1.0.10

Bump magic-filter to 1.0.10

---

CHANGES/1178.feature
aiogram/dispatcher/dispatcher.py

Currently, the method `dp.resolve_used_update_types` can be improved for better readability and understandability, a better name for this function could be "get_registered_event_names", or "get_registered_update_types". 
So I changed the logic, that the dispatcher would automatically collect the update types used in handlers, if `allowed_updates` parameter is not specified.

Automatically Resolve Update Types in `start_polling` method.

---

CHANGES/1232.bugfix.rst
aiogram/types/message.py

Fixed bot assignment in the `Message.send_copy` shortcut

Ensure all message types are assigned to the correct bot.

---

CHANGES/1233.bugfix.rst
aiogram/types/base.py

Updated aiogram/types/base.py to include a model validator which removes any 'UNSET' before field validation. This change was necessary to correctly handle `parse_mode` where 'UNSET' is used as a sentinel value. Without the removal of 'UNSET', it would create issues when passed to model initialization from `Bot.method_name`. 'UNSET' was also added to typing. Tiny documentation fix was made.

Added model validation to remove UNSET before field validation

---

CHANGES/1242.bugfix.rst
aiogram/dispatcher/dispatcher.py
tests/test_dispatcher/test_dispatcher.py

Modified the Dispatcher to remove the "bot" key from workflow_data if found, prior to emitting startup in order to allow manual addition of "bot" to workflow data. This change was necessary as a bot instance is required to start polling, and therefore must be passed correctly. This logic is now tested in the 'test_start_polling' function. The change also includes an update to the changelog.
Fixes #1242

Fix bot instance passing in Dispatcher startup

---

CHANGES/5780.doc.rst
examples/echo_bot.py
examples/echo_bot_webhook.py
examples/echo_bot_webhook_ssl.py
examples/finite_state_machine.py
examples/multibot.py
examples/specify_updates.py
examples/web_app/main.py

Refactor and improve bot examples
Refactored examples code to use aiogram enumerations and enhanced chat messages with markdown beautifications for a more user-friendly display.
`CommandStart()` is now used instead of `Command('start')` for readability.
Furthermore, the bot's 'stop' command was improved, ensuring it executes appropriately during `KeyboardInterrupt `or `SystemExit`.
Additionally, the bot's logging was adjusted to output to `sys.stdout` for better logs' readability.

Refactor and improve bot examples

---

CHANGES/1259.bugfix.rst
aiogram/utils/text_decorations.py
tests/test_utils/test_text_decorations.py

Fixed nested hashtag, cashtag and email message entities not being parsed correctly when these entities are inside another entity.
Fixes: #1259

Fixed nested hashtag, cashtag and email entnties parsing

---

CHANGES/1252.bugfix.rst
aiogram/types/message.py
tests/test_api/test_types/test_message.py

Telegram supports sharing users and chats through convenient UI since [February, 2023](https://core.telegram.org/bots/api#february-3-2023) and while aiogram has support for `user_shared` and `chat_shared` params, it doesn't detect them in `message.content_type` helper. This PR fixes this error.

Fix missing message content types

---

CHANGES/1266.bugfix.rst
aiogram/dispatcher/event/telegram.py
aiogram/dispatcher/router.py
examples/context_addition_from_filter.py
examples/multibot.py
tests/test_dispatcher/test_event/test_telegram.py

Moved global filters check placement into router to add chance to pass context from global filters
into handlers in the same way as it possible in other places
Fixes #1266

Content from global filters

---

CHANGES/1099.doc.rst
examples/error_handling.py

Add error handling example `examples/error_handling.py` where following features used:
- Using error handler: `dp.error`;
- Using error filter: `ExceptionTypeFilter`;
- Using error filter: `ExceptionMessageFilter`;
- Using command object: `CommandObject`;
- Getting `bot` instance passed to a handler;
My motivation is that currently using error handlers is not that obvious.
Locally.
Also, `make lint` was used.
- Windows 10
- Python version: 3.10.8

Add error handling example

---

CHANGES/1269.misc.rst
aiogram/dispatcher/dispatcher.py

Enhanced the warning message in aiogram/dispatcher/dispatcher.py to include a JSON dump of the update. This change helps to give clearer and more detailed information on why an update type is unknown by including the specifics of what the update contains.

Update a warning message in dispatcher

---

docs/contributing.rst

Got similar issue: https://github.com/mu-editor/mu/issues/852
```text
pip install -e .[dev,test,docs,fast,redis,proxy,i18n]
zsh: no matches found: .[dev,test,docs,fast,redis,proxy,i18n]
```
Also:
- added (and checked) Windows cmd examples
- fixed typos
* Operating System: MacOS 13.4.1, Windows 11

Add contributing support for zsh and win

---

CHANGES/1282.bugfix.rst
aiogram/utils/markdown.py

Small bugfix in `utils\markdown.py` which mistakenly applied `html_decoration.quote(...)` inside a Markdown italic variation.

Fix markdown italic quote

---

CHANGES/1281.bugfix.rst
aiogram/utils/magic_filter.py
tests/test_utils/test_magic_filter.py

Modified the ".as_" method in the magic filter class to correctly handle values that are interpreted as `False` such as `0`. Previously, the method incorrectly dismissed these valid values. The issue was identified and fixed to ensure correct handling of all valid data inputs.
Fixes #1281

Fix magic operation `.as_` for values interpreted as False

---

CHANGES/1290.bugfix.rst
aiogram/methods/base.py
aiogram/types/base.py
tests/test_api/test_methods/test_base.py

Fixed error overlapping when validation error is caused by `remove_unset` root validator in base types and methods.
```python
InlineKeyboardButton(
text="Play with Friends",
switch_inline_query_chosen_chat="test",
)
```
```
.../aiogram/types/base.py", line 31, in remove_unset
return {k: v for k, v in values.items() if not isinstance(v, UNSET_TYPE)}
AttributeError: 'str' object has no attribute 'items'                                                                                                                      
```
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for InlineKeyboardButton
switch_inline_query_chosen_chat
Input should be a valid dictionary or instance of SwitchInlineQueryChosenChat [type=model_type, input_value='test', input_type=str]
For further …
```

Fixed error overlapping when validation error is caused by remove_unset root validator in base types and methods.

---

CHANGES/1293.feature.rst
aiogram/utils/media_group.py
docs/utils/index.rst
docs/utils/media_group.rst
tests/test_api/test_methods/test_base.py
tests/test_utils/test_media_group.py

Implemented a MediaGroupBuilder class in 'aiogram/utils/media_group.py' to help construct media groups. The class supports addition of different media types (audio, photo, video, document) to the media group with a maximum limit of 10 files. The functionality is demonstrated and usage is documented in 'docs/utils/media_group.rst'. Added related test cases in 'tests/test_utils/test_media_group.py'. This is to streamline and simplify the process of media group creation

Added MediaGroupBuilder for media group construction

---

CHANGES/1262.feature
aiogram/utils/deep_linking.py
aiogram/utils/payload.py
pyproject.toml
tests/test_utils/test_deep_linking.py

Added support for custom encoders/decoders
Fixes #1262

Custom encoding support

---

aiogram/utils/deep_linking.py
examples/multibot.py
tests/test_utils/test_deep_linking.py

Applied
```
make lint
make reformat
```

Apply lint&reformat for existing code

---

CHANGES/1317.bugfix.rst
aiogram/fsm/middleware.py
tests/test_issues/test_1317_state_vs_isolation.py

Fixed priority of events isolation, now user state will be loaded only after lock is acquired.
Fixes #1317

Fixed priority of events isolation

---

docs/dispatcher/class_based_handlers/message.rst

I've found a broken link in `MessageHandler` (Class based handlers) documentation. Here's a fix for it.

Fix broken link in MessageHandler (CBH) documentation

---

CHANGES/1331.misc
aiogram/dispatcher/dispatcher.py
aiogram/webhook/aiohttp_server.py

This is a backport of #1328 to mitigate possible issues like #628, #927. As in #1328, this PR preserves asyncio `Task` pointers until the task is completed to ensure `Task` will not be garbage collected and disappear. See recommendations in [Python docs](https://docs.python.org/3/library/asyncio-task.html#creating-tasks).
> **Important**: Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection
Honestly, I don't have a v3-based bot with workload I have in v2. But want to admit once again, it's a pretty rare case and we're …

Prevent update handling task pointers from being garbage collected, backport of #1328

---

CHANGES/1332.bugfix.rst
aiogram/types/message.py
tests/test_api/test_types/test_message.py

If you set default parse mode on Bot instance, this parse mode applies on all calls with UNSET parse mode, even on `send_copy`, where entities are already applied and no parse mode is required. It even breaks copying regular messages with 'special' characters like `.` or `!` when `MarkdownV2` is set by default. 
Parse mode should not be sent, but we need to have an option to override it. So, by default `parse_mode` in `send_copy` should be `None.
* Operating System: macOS

Fix send_copy helper parse mode

---

CHANGES/1347.misc.rst
pyproject.toml

This commit changes the version requirements for typing-extensions in the dependencies section of pyproject.toml file. This change now requires versions that are greater than or equal to 4.7.0 and less than or equal to 5.0. The previous version, 4.8.0, has been found to cause compatibility issues with some other libraries.
Fixes #1347

Update typing-extensions version range in dependencies

---

CHANGES/1357.misc.rst
aiogram/dispatcher/event/handler.py
tests/test_dispatcher/test_event/test_handler.py

new improved CallableMixin
all internal aiogram tests

new improved CallableMixin

---

CHANGES/1361.misc
pyproject.toml

New pydantic released
https://github.com/pydantic/pydantic/releases/tag/v2.5.0

Add pydantic 2.5 support

---

CHANGES/1320.misc.rst
pyproject.toml
tests/conftest.py
tests/test_api/test_client/test_session/test_aiohttp_session.py
tests/test_fsm/storage/test_isolation.py

Fixed ResourceWarning in tests, modified the pytest's configuration file, `pyproject.toml`, to remove filterwarnings settings. It also makes changes in various test files; the Redis isolation test is now using the provided `redis_storage` fixture instead of setting up its own connection, pytest.mark.filterwarnings is no longer used in `test_isolation.py` and `test_aiohttp_session.py` properly closes off sessions.
Fixes #1320

Fixed ResourceWarnings in tests

---

CHANGES/1368.bugfix.rst
aiogram/__init__.py
aiogram/filters/callback_data.py
tests/test_filters/test_callback_data.py
tests/test_fsm/test_state.py

Fixes #1368
Method `.is_required()` returns `True` on `Optional[int]` without default value, because it's still requires either `int` or `None` value.
On the other hand, when we parse a value from a zero-length string - it cannot be converted to `None` or an `int`, so pyantic returns an error about it.
The solution to this problem is to adapt the field type check to such a case.

Fix CallbackData without default Optional

---

.butcher/enums/KeyboardButtonPollTypeType.yml
CHANGES/1398.feature.rst
aiogram/enums/__init__.py
aiogram/enums/keyboard_button_poll_type_type.py
docs/api/enums/index.rst
docs/api/enums/keyboard_button_poll_type_type.rst

A new enum `KeyboardButtonPollTypeType` for `KeyboardButtonPollTypeType.type` field has bed added.

Add KeyboardButtonPollTypeType enum

---

CHANGES/1403.bugfix.rst
aiogram/types/message.py

with the 7.0 changes `reply_parameters` has been added everywhere except for `messages.send_copy`, this PR aims to fix that

Update message.send_copy: add missing reply_parameters param

---

CHANGES/1395.doc.rst
docs/utils/i18n.rst

Add notion "Working with plural forms" in documentation Utils -> Translation to clearify using `gettext` from `aiogram.utils.i18n`.
Fixes #1395
* Operating System: Windows
* Python version: Pyrhon 3.10

Add notion Working with plural forms in documentation

---

CHANGES/1418.bugfix.rst
aiogram/client/session/base.py
tests/test_api/test_client/test_session/test_base_session.py

Fixed JSON serialization of the `LinkPreviewOptions` class while it is passed
as bot-wide default options.

Fixed default LinkPreviewOptions JSON serialization

---

CHANGES/1453.bugfix.rst
aiogram/enums/content_type.py
aiogram/types/message.py
tests/test_api/test_methods/test_add_sticker_to_set.py
tests/test_api/test_methods/test_create_new_sticker_set.py
tests/test_api/test_methods/test_set_sticker_set_thumbnail.py
tests/test_api/test_types/test_message.py

* Adding `SHARED_USER` in `ContentType` enum
* Adding tests for SharedUser, business_connection_id, is_from_offline, sender_business_bot
#1446
\* InputSticker now requires format as in [Telegram Bot API](https://core.telegram.org/bots/api#inputsticker)
* Operating System: Arch Linux x86_64
* Python version: 3.11.8

Fixing tests and content types for Telegram Bot API 7.2 update

---

CHANGES/1468.feature.rst
aiogram/client/bot.py
docs/index.rst
examples/without_dispatcher.py
tests/test_api/test_client/test_bot.py

The bot client now supports the context manager protocol, providing automatic resource management. This enhancement helps to automatically close the session when leaving the context, which cleans up resources better. The documentation and tests have been updated accordingly to illustrate this new feature. Moreover, an example of usage without a dispatcher has been provided to clarify its use in simple cases.
From now you can use:
```python
async with Bot(...) as bot:
...
```
instead of
```python
async with Bot(...).context():
...
```

Add context manager support for bot client

---

CHANGES/1458.bugfix.rst
aiogram/dispatcher/dispatcher.py

No error logging when handle_in_background=True
There were no error logging when in handle_in_background=True mode. I changed the call to the one used in synchronous handling mode

Fix missing error logging

---

docs/dispatcher/filters/command.rst

Fix rendition of the backslash in regular expressions
Regexp expressions were rendered incorrectly in docs.

Fixed display of regular expressions in documentation

---

CHANGES/1482.misc.rst
examples/echo_bot.py
examples/echo_bot_webhook.py
examples/echo_bot_webhook_ssl.py
examples/error_handling.py
examples/finite_state_machine.py
examples/multi_file_bot/bot.py
examples/multi_file_bot/handlers/start.py
examples/quiz_scene.py
examples/scene.py
examples/specify_updates.py
examples/web_app/handlers.py
examples/web_app/main.py

Enhanced the consistency of the codebase by updating the instantiation of the `bot` instance.
None
Followed steps on: https://docs.aiogram.dev/en/dev-3.x/contributing.html
* Operating System: MacOS Sonoma 14.4.1
* Python version: 3.11.7

misc: code consistency and bot instance creation

---

aiogram/client/bot.py
aiogram/methods/__init__.py
examples/multibot.py
tests/test_utils/test_formatting.py

Just applied `isort` from contribution guide

Apply isort 

---

CHANGES/1500.bugfix.rst
aiogram/client/session/aiohttp.py

Add DNS cache ttl setting to aiohttp session.
Also the limit argument is added to the session initializer.
This commit adds a setting for DNS cache ttl (time-to-live) to the aiohttp session configuration. This is implemented as a workaround for a known issue in aiogram as exhibited in aiogram/aiogram#1500.

Add DNS cache ttl setting to aiohttp session.

---

CHANGES/1450.feature.rst
aiogram/client/session/aiohttp.py
aiogram/types/custom.py
aiogram/utils/serialization.py
docs/migration_2_to_3.rst
docs/utils/index.rst
docs/utils/serialization.rst
tests/test_utils/test_serialization.py

Introduced utilities to deserialize Telegram objects to JSON-compliant Python objects and vice versa. These utilities manage both cases with and without files. The documentation has been updated to reflect these changes, including updates in migration recommendations and tutorials. A new unit test is added to verify the new functionality.
Fixes #1450

Add serialization utilities and update documentation

---

.butcher/types/Message/aliases.yml
CHANGES/1538.misc.rst
aiogram/types/message.py
tests/test_api/test_types/test_message.py

Added method `Message.as_reply_parameters(...)`.
Replaced usage of the argument `reply_to_message_id` with `reply_parameters` in all Message reply methods.
Fixes: #1538

Added 'as_reply_parameters' method & integrate with message reply methods

---

docs/api/defaults.rst

Fix parameter name `default`.
The parameter name is `default` in bot.py instead of `defaults`.

chore(docs): fix in `defaults.rst` change Bot parameter name to `default`.

---

CHANGES/1538.misc.rst
CHANGES/1546.bugfix.rst
examples/web_app/routes.py

Fixed URL path in the "Open" button at the "demo/sendMessage" endpoint in the web_app example. 
The button should open the web application, but at the moment it sends a GET request to the current endpoint (which only accepts POST requests).

Fix web_app example

---

CHANGES/1507.misc.rst
aiogram/fsm/state.py

To prevent runtime calculating we should pre-calculate StateGroup values
* Operating System: macOS

Precalculate StateGroup values

---

CHANGES/1474.feature.rst
aiogram/dispatcher/middlewares/user_context.py
tests/test_dispatcher/test_middlewares/test_user_context.py

Add getting user from `chat_boost`

---

.butcher/types/ExternalReplyInfo/default.yml
.butcher/types/InputTextMessageContent/default.yml
CHANGES/1543.bugfix.rst
aiogram/client/bot.py
aiogram/methods/edit_message_text.py
aiogram/types/input_text_message_content.py
aiogram/types/message.py

Fixed link preview options to use global defaults in various types and methods to use global defaults for `link_preview_options`.
This change ensures consistency and enhances flexibility in handling link preview options across different components.
Fixes #1543

Fixed link preview options to use global defaults in some types and methods

---

CHANGES/1577.feature.rst
pyproject.toml

I think the upper bound can be removed altogether, since aiogram only uses aiofiles.open, which is unlikely to ever be changed. Let me know what you think is best.

Bump aiofiles version upper bound to <24.2

---

CHANGES/1579.bugfix.rst
aiogram/types/__init__.py
aiogram/types/update.py
pyproject.toml
tests/test_dispatcher/test_dispatcher.py

Fixed `Default` object annotation resolution in `pydantic` models.
Reformat code.
Fixes: #1579

#1579 Fixed `Default` object annotation resolution in `pydantic` models.

---

CHANGES/1584.bugfix.rst
tests/test_utils/test_chat_action.py

Hey :wave: Arch Linux maintainer here.
This fixes a `PytestDeprecationWarning` thrown when running the tests. This warning was introduced in pytest-asyncio in https://github.com/pytest-dev/pytest-asyncio/pull/648.

Fix pytest-asyncio deprecation warning in test

---

CHANGES/1599.doc.rst
docs/utils/formatting.rst

Add missing closing tag for bold

Add missing closing bold tag in the docs

---

CHANGES/1602.bugfix.rst
aiogram/filters/callback_data.py
tests/test_filters/test_callback_data.py

From now UUID will have 32 bytes length instead of 36 bytes.

Fixed UUID (and other types) serialization in the CallbackData factory.

---

CHANGES/1608.misc.rst
aiogram/utils/text_decorations.py

Reuse constant for the `tg-emoji` closing tag

[misc] fix tg-emoji closing tag: use constant

---

CHANGES/1615.misc.rst
pyproject.toml

The aiohttp version in the project is outdated and has a number of vulnerabilities.
When installing additional libraries into a project, conflicts arise that cannot be resolved while the aiohttp version is limited to <3.11
Fixes #1614
`pytest test`
* Operating System: MacOs
* Python version: 3.12.4

Increased aiohttp version

---

docs/locale/uk_UA/LC_MESSAGES/migration_2_to_3.po
docs/migration_2_to_3.rst

Fix link formatting for pydantic in migration docs (migration_2_to_3.po and migration_2_to_3.rst)

Fix link formatting

---

CHANGES/1631.misc.rst
pyproject.toml

Added support for redis 5.1 and 5.2 versions. Release notes: https://github.com/redis/redis-py/releases
New feature (non-breaking change which adds functionality)
Running `pytest --redis redis://<host>:<port>/<db> tests` results in `1539 passed, 22 skipped in 11.21s`.
* Operating System: Fedora 41
* Python version: 3.13.1

Bump redis max version to <5.3.0

---

CHANGES/1630.bugfix.rst
aiogram/utils/deep_linking.py
tests/test_utils/test_deep_linking.py

The regex pattern which identifies the "bad characters" for [deeplink payload](https://core.telegram.org/bots/features#deep-linking) is not correct:
```python
import re
print(f"{ord('A')=}")
print(f"{ord('Z')=}")
print(f"{ord('a')=}")
print(f"{ord('z')=}")
print("-----------------------------------")
for i in range(91, 97):
print(f"{i}: {chr(i)}")
print("-----------------------------------")
print(re.search(r"[^A-z0-9-]", "hi`bye"))      # None
print(re.search(r"[^A-Za-z0-9-_]", "hi`bye"))  # <re.Match object; span=(2, 3), match='`'>
```
There is a gap between `Z` and `a`. We should explicitly include the ranges `A-Z` and `a-z` to avoid accepting characters like backtick.
I modified the `WRONG_PAYLOADS` list in `tests/test_utils/test_deep_linking.py` to demonstrate the bug.
**Test …

Fix `BAD_PATTERN` regex in deeplinking process.

---

CHANGES/1595.bugfix.rst
aiogram/utils/keyboard.py
tests/test_utils/test_keyboard.py

Since `KeyboardBuilder` is not restricted to be created directly, we should avoid case with zero max width.
Fixes #1595

Prevent endless loop with buttons

---

CHANGES/1641.bugfix.rst
aiogram/client/default.py
aiogram/fsm/scene.py
aiogram/utils/class_attrs_resolver.py
aiogram/utils/dataclass.py
tests/test_fsm/test_scene.py
tests/test_utils/test_class_attrs_resolver.py
tests/test_utils/test_dataclass.py

Previously, `Scene` handlers were registered based on the sorted output of `inspect.getmembers`, causing incorrect execution order. Now, handlers are registered in the order they are defined in the class, ensuring reliable behavior and proper sequence when handling filters with varying specificity. Added test cases to validate the correct handler ordering.
Fixes: #1641

Fix handler registration order in `Scene`

---

CHANGES/1637.feature.rst
aiogram/dispatcher/middlewares/data.py
docs/dispatcher/dependency_injection.rst
pyproject.toml

Add TypedDict definitions for middleware context data to the dispatcher dependency injection docs.
So, now you can use `aiogram.dispatcher.middleware.data.MiddlewareData` directly or
extend it with your own data in the middlewares.
Fixes #1637

Typed data

---

CHANGES/1648.feature.rst
aiogram/utils/deep_linking.py
tests/test_utils/test_deep_linking.py

Added support [deep links to open Mini Apps](https://core.telegram.org/api/links#main-mini-app-links) 
```python
from aiogram.utils.deep_linking import create_startapp_link
link = await create_startapp_link(bot, 'foo')
```
* Operating System: Mac OS Sequoia 15.3.1

Added support of "startapp" deep links

---

CHANGES/1659.misc.rst
pyproject.toml

Bump pydantic upper bound from <2.11 to <2.12.
Upgrading `pydantic` to version 2.11 significantly reduces resource consumption
pydantic blog post: https://pydantic.dev/articles/pydantic-v2-11-release

chore: bump `pydantic` upper bound from <2.11 to <2.12

---

CHANGES/1657.feature.rst
aiogram/utils/formatting.py
tests/test_utils/test_formatting.py

New methods for `aiogram.utils.formatting.Text`:
- `as_caption_kwargs()`
- `as_poll_question_kwargs()`
- `as_poll_explanation_kwargs()`
- `as_gift_text_kwargs()`
Fixes #1656 

Add different shortcut methods for Text.as_kwargs()

---

CHANGES/1661.misc.rst
aiogram/dispatcher/event/handler.py

Replaced `loop.run_in_executor` with `asyncio.to_thread` for improved readability and consistency.  
This change does not affect functionality but simplifies the code.  
No related issue.
Since this is a non-functional change, no new tests were required.  
Existing tests were run to ensure there were no regressions.

misc: simplify running non-async callback using asyncio.to_thread

---

CHANGES/1666.doc.rst
docs/dispatcher/router.rst

This pull request fixes issue #1653, where code blocks in the documentation were broken due to incorrect indentation. The affected syntax was:
```rst
.. code-block:: python
:caption: module_1.py
:name: module_1
```
The issue was caused by a missing indentation for the `:name:` directive, which broke Sphinx rendering. The fix was straightforward and involved properly aligning directive options under the `.. code-block::` line.
Additionally, this PR supersedes #1654, which aimed to fix the same issue but has been inactive for over three weeks.
Fixes #1653  
Closes #1654
Tested by cloning the repository and building the documentation locally using Sphinx. The affected code blocks now render correctly without any warnings or formatting issues. …

[#1653, #1654] docs: fix code block formatting in router.rst

---

CHANGES/1658.bugfix.rst
aiogram/dispatcher/dispatcher.py
tests/test_dispatcher/test_dispatcher.py

Introduce a semaphore-based mechanism to control the number of concurrent tasks in polling mode when `handle_as_tasks=True`. Added the `tasks_concurrency_limit` parameter to `start_polling()` and `run_polling()`, preventing potential memory exhaustion during high update loads.
Fixes #1658

Add semaphore support for limiting concurrent updates

---

CHANGES/1672.bugfix.rst
aiogram/fsm/scene.py
docs/dispatcher/finite_state_machine/scene.rst
tests/test_fsm/test_scene.py
tests/test_issues/test_1672_middleware_data_in_scene.py

Fixed an issue where the scene entry handler (`enter`) was not receiving data passed to the context by middleware, which could result in a `TypeError`.
Fixes #1672 
Is an alternative solution to #1673

fix: ensure middleware data is passed to scene entry handler

---

aiogram/webhook/aiohttp_server.py

Resolves warning "Expected type 'None', got 'Application' instead"
Before:
After:

fix: resolve warning "Expected type 'None', got 'Application' instead"

---

CHANGES/1685.feature.rst
aiogram/fsm/scene.py
tests/test_fsm/test_scene.py

#1684 
Add support for `State` type in scenes methods like `goto`, `enter`, `get`
Calm down MyPy

Add support for `State` type in scenes methods

---

CHANGES/1683.feature.rst
aiogram/exceptions.py
aiogram/fsm/context.py
aiogram/fsm/scene.py
aiogram/fsm/storage/base.py
aiogram/fsm/storage/memory.py
aiogram/fsm/storage/mongo.py
aiogram/fsm/storage/redis.py
tests/test_fsm/storage/test_storages.py

#1682 
Refactor FSM Storage methods input types to calm down MyPy.
Refactored:
- `FSMContext.set_data`
- `FSMContext.update_data`
- `BaseStorage.set_data`
- `BaseStorage.update_data`
- `BaseStorage`'s child methods
- `SceneWizard.set_data`
- `SceneWizard.update_data`
1 test edited to cover new code

Refactor FSM Storage methods input types to calm down MyPy.

---

CHANGES/1700.misc.rst
pyproject.toml

Bumped `aiohttp` maximum version to `3.13`. This makes `aiogram` compatible with other packages that have `aiohttp>=3.13` requirement.
* Operating System: Windows
* Python version: Python 3.13.2

Relax aiohttp versions range
