aiogram/aiogram

- aiogram/types/message.py
Supplementary state `left_chat_member` for existing state `new_chat_members`.
Maybe useful to monitor if the bot was kicked from the group chat.
> Added left_chat_member state to the Message class

- aiogram/bot/base.py
- aiogram/contrib/fsm_storage/redis.py
- aiogram/dispatcher/__init__.py
- aiogram/dispatcher/middlewares.py
- aiogram/utils/versions.py
- examples/webhook_example.py
> More typos fix

- aiogram/types/message.py
> Make Message's get_command method return pure command

- aiogram/bot/bot.py
- dev_requirements.txt
- tests/test_bot.py
- tests/types/dataset.py
Let's start to test it! :)
It's all about tasks https://github.com/aiogram/aiogram/issues/8 and  https://github.com/aiogram/aiogram/issues/9
> First pytests

- aiogram/types/message.py
- tests/types/dataset.py
Ability to handle group converting events by content_type. 
I.e. 
```@dp.message_handler(content_types=types.ContentType.MIGRATE_FROM_CHAT_ID)```
> Converting group to supergroup event

- aiogram/dispatcher/filters.py
```python
import timeit
exc = Exception()
def check_raise():
try:
raise exc
except Exception:
return True
except:
return False
def check_inst():
return isinstance(exc, Exception)
>>> timeit.timeit(check_raise)
0.6126432769233361
>>> timeit.timeit(check_inst)
0.15042719698976725
```
> Improve check in ExceptionsFilter

- aiogram/types/user.py
No need to check for babel because it is in requirements now
> Babel is not in requirements

- examples/webhook_example_2.py
Simple example with webhook executor
> Simple example with webhook executor

- aiogram/types/message.py
Quick way to edit reply markup by message method
> Add edit_reply_markup method to Message class

- aiogram/types/message.py
> fix message.py imports

- aiogram/bot/base.py
Bug fix for https://github.com/aiogram/aiogram/issues/65
> #65 bug fix with no proxy_auth

- docs/source/index.rst
Python version 3.6 -> 3.7 to docs
> Python version 3.6 -> 3.7 to docs

- aiogram/types/page_selection_location.py
- aiogram/utils/parts.py
- examples/inline_buttons_pagination.py
`aiogram` didn't yet have inline buttons pagination functionality. This PR fixes that.
This PR has been tested in my KGJiraBot and on included examples.
* Operating System: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
* Python version: Python 3.7.1
> Inline buttons pagination

- aiogram/types/message.py
Added specific checks for captions_entities to parse
Manually
> Fixed entities parsing for captions

- aiogram/dispatcher/dispatcher.py
- tests/test_dispatcher.py
If user provides wrong data to 'bot' argument, raised exceptions are not clear to fix issue.
> Check bot instance on Dispatcher __init__

- aiogram/dispatcher/filters/builtin.py
Example of use
```python
_ = i18n.lazy_gettext
@dp.message_handler(text=_("Hello"))
async def hello(message: types.Message):
await message.reply(_("Hi!"))
```
> Made Text filter ready for lazy_gettext

- aiogram/dispatcher/filters/__init__.py
- aiogram/dispatcher/filters/filters.py
- aiogram/dispatcher/handler.py
> Optimize filter checking

- aiogram/bot/base.py
- aiogram/bot/bot.py
- aiogram/types/message.py
- Fix [aiogram_ru/54632](https://t.me/aiogram_ru/54632)
- Type hint
> Type hint and fix parse_mode parameter

- aiogram/bot/api.py
> Make check_result func sync

- aiogram/bot/base.py
- aiogram/types/mixins.py
> Add get_url method for Downloadable

- aiogram/bot/base.py
#100
Trying to implement different bot tokens at the same time. This implementation is very similar to the implementation of timeouts.
> Different bot tokens

- examples/i18n_example.py
- examples/locales/mybot.pot
- examples/locales/ru/LC_MESSAGES/mybot.po
More powerful i18n example with pluralization support and some useful parser tags
> Update i18n example

- aiogram/types/mixins.py
Fixes #143
- Created message handler described in #143, send image to bot, got saved file without errors.
* Operating System: Arch Linux
* Python version: 3.7.3
> Fix #143: Imposible to download file into directory

- examples/finite_state_machine_example.py
unify finishing state machine interaction
> FSM example: unify finishing state machine interaction 

- examples/inline_keyboard_example.py
- examples/regular_keyboard_example.py
Add examples how to use both reply and inline keyboards. Closes #76
> Add keyboards usage examples

- aiogram/types/input_media.py
Changed type of parse_mode in input_media.py
Fixes #161
It was not tested  ¯\\_(ツ)_/¯
> Fixed parse_mode type

- examples/broadcast_example.py
- examples/callback_data_factory.py
- examples/check_user_language.py
- examples/finite_state_machine_example.py
- examples/inline_bot.py
- examples/media_group.py
- examples/middleware_and_antiflood.py
- examples/payments.py
- examples/proxy_and_emojize.py
- examples/throtling_example.py
- examples/webhook_example.py
- examples/webhook_example_2.py
executor.loop = dispatcher.loop = bot.loop = asyncio.get_event_loop() by default
> remove unnecessary loop definitions

- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/filters/builtin.py
Add inline_query_handlers to Text and Regexp bind
Fix type hints
Fixes #164 
> Fix builtin filters

- aiogram/dispatcher/filters/builtin.py
Fix ignore_case support in the Text filter
Fixes #169
Tests from #170 are passed.
> Add ignore_case support in Text filter. Fixes #169

- aiogram/dispatcher/handler.py
The wrapped functions can be handler now. AFAIK it won't break anything
Fixes #179
> Wrapped function can be registered as handler

- aiogram/types/chat_member.py
- tests/types/test_chat_member.py
- Deprecated methods removed
- Added new RESTRICTED status
- is_chat_member method has been updated: user could be restricted but remain a member.
- Added tests for chat_member
Motivation: [aiogram_ru/67461](https://t.me/aiogram_ru/67461)
* Python version: 3.7.3
> ChatMember update

- docs/source/install.rst
Added aiogram AUR package installation instructions to Installation section of docs
> Add aiogram AUR package installation instructions

- aiogram/bot/bot.py
I think it should work
[Traceback](https://pastebin.com/6mdJVqYL)
Discussion: [aiogram#2135](https://t.me/aiogram/2135)
> Fix error with set_chat_permissions

- aiogram/dispatcher/dispatcher.py
fixed call of set_result on close_waiter future of dispatcher, fixes #200 
- [v] Bug fix (non-breaking change which fixes an issue)
> fix set_result of close_waiter future on polling end

- aiogram/dispatcher/dispatcher.py
Exit dispatcher polling loop on CancelledError, fixes #199 
- [v] Bug fix (non-breaking change which fixes an issue)
> process cancellation in dispatch polling

- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/filters/builtin.py
- docs/source/dispatcher/filters.rst
Add IsReplyFilter
```py
@dp.message_handler(is_reply=True)
async def reply_test(msg, reply):
await msg.answer(f'Reply: {reply.text}')
```
> add IsReplyFilter

- aiogram/utils/executor.py
Fixes [aiogram_ru/112353](https://t.me/aiogram_ru/112353)
> Fix incorrect completion order.

- docs/source/install.rst
Add `aiohttp[speedups]` in installation recommendations
Includes `cchardet` and `aiodns`.
> Add aiohttp speedups in installation recommendations

- aiogram/types/base.py
Added type annotations to `aiogram.types.base` module
> add typing

- aiogram/utils/deprecated.py
Checking arguments and warning are duplicated for regular function and coroutine. Duplicate code moved to the `_handling` method.
Slight readability improvement.
> refactor(utils): reduce code duplication

- aiogram/types/chat.py
Use one default argument across project: `as_html=True`
Via project tests
> Unify default as_html argument

- docs/source/install.rst
aiogram is a framework, not a library
> #195 aiogram is a framework

- aiogram/bot/api.py
- tests/test_bot/test_api.py
Added check: right part of token is exists.
Removed check: left part of token is longer than 3 symbols
Added test cases from issue.
Also added token type validation and test cases for it.
Fixes #239 
Fixes token type validation (not issued)
> #239 check_token fix

- aiogram/bot/api.py
- aiogram/bot/bot.py
- aiogram/types/animation.py
- aiogram/types/audio.py
- aiogram/types/chat.py
- aiogram/types/chat_member.py
- aiogram/types/chat_photo.py
- aiogram/types/document.py
- aiogram/types/file.py
- aiogram/types/passport_file.py
- aiogram/types/photo_size.py
- aiogram/types/sticker.py
- aiogram/types/video.py
- aiogram/types/video_note.py
- aiogram/types/voice.py
Bot API [4.5](https://core.telegram.org/bots/api#december-31-2019)
- New ```file_unique_id```, ```small_file_unique_id```, ```big_file_unique_id```, ```custom_title```, ```slow_mode_delay``` fields
- New setChatAdministratorCustomTitle method
- MarkdownV2 style [will add](https://t.me/aiogram_ru/138086) @JrooTJunior .
It hasn't been tested.
> Bot API 4.5 (without MarkdownV2)

- docs/dispatcher/router.md
Typo at https://dev-docs.aiogram.dev/dispatcher/router/ which causes `SyntaxError`.
> Delete unnecessary colons

- README.md
> aiogram dev

- aiogram/bot/bot.py
- aiogram/contrib/middlewares/logging.py
- aiogram/dispatcher/dispatcher.py
- aiogram/types/__init__.py
- aiogram/types/message_entity.py
- aiogram/types/poll.py
- aiogram/types/reply_keyboard.py
- aiogram/types/update.py
- aiogram/types/user.py
Bot API 4.6
WARNING: I don't add new poll_answer_handlers to any builtin filters, because I think it requires discussion.
Fixes #264
Manually by @JrooTJunior
> Bot API 4.6

- aiogram/types/reply_keyboard.py
Fixed missing `request_poll` in `aiogram.types.KeyboardButton.__init__`
[Discussion (ru)](https://t.me/aiogram_ru/148782)
by @gabbhack
> Fix reply_keyboard.py

- README.md
- README.rst
- aiogram/__init__.py
- aiogram/bot/api.py
- aiogram/utils/text_decorations.py
- docs/source/index.rst
- docs/source/install.rst
> Fix some typos and grammatical mistakes

- aiogram/bot/bot.py
Added default parse mode for send_animation method
Fixes #292
> Added default parse mode for send_animation method

- README.md
Fixed issue https://github.com/opencollective/opencollective/issues/2668 with organization's avatar display
> OpenCollective organization display fix

- README.md
Updated telegram version shield in README
> Updated telegram version shield

- aiogram/dispatcher/webhook.py
Fix https://t.me/aiogram_ru/185063
> fix AttributeError

- aiogram/types/message.py
Added 2 new methods to types.message that send dice
> add answer_dice method

- aiogram/bot/base.py
- tests/__init__.py
- tests/test_bot.py
> #296 Get bot's user_id without get_me

- aiogram/dispatcher/dispatcher.py
One line fix for user context at poll_answer (introduced with API 4.6)
> fix: change user context at poll_answer

- aiogram/api/client/session/aiohttp.py
- aiogram/api/client/session/base.py
- aiogram/api/methods/base.py
- docs/api/client/session/aiohttp.md
- mkdocs.yml
- tests/test_api/test_client/test_session/test_aiohttp_session.py
- tests/test_api/test_client/test_session/test_base_session.py
0. Implement methods with timeout
0. Get rid of complexity creating new http-session manager
Has not been test anyhow yet.
```python
from aiogram import Bot
from aiogram.api.methods import SendMessage
async def main():
bot = Bot("...")
request = SendMessage(
chat_id=124191486,
text="text",
request_timeout=10
)
print(request.request_timeout)
await request.emit(bot)
import asyncio
asyncio.get_event_loop().run_until_complete(main())
```
> Dev 3.x refactor sessions

- .isort.cfg
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
Add pre-commit hooks with black, isort, flake8 and some other useful tools.
> feat: add pre-commit hooks

- aiogram/api/types/callback_query.py
- aiogram/api/types/inline_query.py
- aiogram/api/types/pre_checkout_query.py
- aiogram/api/types/shipping_query.py
- docs/api/methods/answer_callback_query.md
- docs/api/methods/answer_inline_query.md
- docs/api/methods/answer_pre_checkout_query.md
- docs/api/methods/answer_shipping_query.md
- docs/api/types/callback_query.md
- docs/api/types/inline_query.md
- docs/api/types/pre_checkout_query.md
- docs/api/types/shipping_query.md
- tests/test_api/test_types/test_callback_query.py
- tests/test_api/test_types/test_inline_query.py
- tests/test_api/test_types/test_pre_checkout_query.py
- tests/test_api/test_types/test_shipping_query.py
- Add CallbackQuery.answer
- Add InlineQuery.answer
- Add PreCheckoutQuery.answer
- Add ShippingQuery.answer
* Operating System: Kubuntu 20.04
* Python version: 3.8.2
> Answer aliases

- aiogram/api/types/chat_member.py
- docs/api/types/chat_member.md
- tests/test_api/test_types/test_chat_member.py
* Operating System: MacOS Catalina 10.15.4
> Added fields to ChatMember

- aiogram/utils/markdown.py
Fix usages of markdown helper methods
Fixes #350
> fix: markdown helper methods work correctly

- aiogram/dispatcher/filters/builtin.py
Add possibility to pass commands in captions: photo, video, audio, etc. This change doesnt break backward compatibility.
Example usage:
```python3
@dp.message_handler(commands=['myCommand'], commands_ignore_caption=False, content_types=ContentType.ANY)
@dp.message_handler(Command(['myCommand'], ignore_caption=False), content_types=[ContentType.TEXT, ContentType.DOCUMENT])
```
New feature (non-breaking change which adds functionality)
Tested on own bot in many cases.
> Command filter with caption check

- aiogram/utils/exceptions.py
Added new exception that happens  when you try to pin deleted or unknown message
> Add exception MessageToPinNotFound

- aiogram/types/callback_query.py
Fixes CallbackQuery.answer() returns nothing. Expected: bool
> Fix CallbackQuery.answer() returns nothing

- aiogram/contrib/fsm_storage/redis.py
all in title
Nikak, cause nothing to test
> comment of RedisStorage2 fix

- aiogram/types/animation.py
https://core.telegram.org/bots/api#animation
Add missing attributes for Animation class
> Fix missing attributes for Animation class

- README.md
readme file editions.
Fixes #403
> docs(readme): prettify readme, update downloads stats badge

- aiogram/types/message.py
> Add missed emoji argument to reply_dice

- aiogram/utils/exceptions.py
Specify BadRequest exceptions for big files and system messages (like pins)
New feature (non-breaking change which adds functionality)
On my bot
> new: add exceptions

- aiogram/utils/exceptions.py
New error text
`BadRequest: Reply message not found`
> Fixed MessageToReplyNotFound match text

- aiogram/types/input_file.py
❤️ This change allows the Pathlib library to be used as a path reference for InputFile!
> feat(InputFile): adding Pathlib to supporting types for files

- README.md
Telegram API shields update
4.9 -> 5.0
> Telegram API shields update

- aiogram/types/input_media.py
> fixed: Cannot send playlist of audio files

- aiogram/types/input_message_content.py
Replaced the optionality of properties with more relevant ones.
Add `vcard` argument to InputContactMessageContent constructor
Run all tests in tests folder
* Operating System: Manjaro 20.2
* Python version: 3.8.6
> Fixed optionality of some properties, add vcard argument to InputContactMessageContent constructor

- aiogram/utils/exceptions.py
Add exception MessageIdInvalid
> Add exception MessageIdInvalid

- aiogram/utils/executor.py
> Correct a typo in executor.py

- aiogram/dispatcher/storage.py
setdefault to actually return the proper value
Fixes issue #405
Bug fix (non-breaking change which fixes an issue)
> fix return value of FSMContextProxy's setdefault (#405)

- dev_requirements.txt
- tests/test_bot.py
- tests/test_dispatcher.py
- tests/test_message.py
- pytest updated
- yield_fixture deprecation fixed
- event_loop removed
> pytest update; yield_fixture deprecation fix; event_loop removed

- docs/source/install.rst
Update installation guide as the package is now available in the official repository.
n/a
> Update installation instruction for Arch

- docs/source/install.rst
> Docs: fix typo "form" -> "from"

- aiogram/types/message.py
Addded answer_chat_action() method for types.Message which allows to use send_chat_action() method directly from recieved message.
> Added answer_chat_action() method for types.Message

- aiogram/utils/exceptions.py
ADD Exceptions:
* CantRestrictChatOwner
* UserIsAnAdministratorOfTheChat
> Add restrict exceptions

- aiogram/utils/parts.py
Added split_separator parameter, to **safe_split_text** function, to select a text delimiter.
This is pretty simple update, and I don't know how exactly I am supposed to test in properly. 
* Operating System: Manjaro 5.4.89
* Python version: Python 3.9.1
> Added split_separator param to safe_split_text

- aiogram/types/chat.py
> Add Chat.message_auto_delete_time field

- examples/chat_type_filter.py
Channels require a separate channel_post_handler, so this example is currently broken and confusing
Manually
> [examples] Changed ChatType from CHANNEL to SUPERGROUP to avoid confusion

- aiogram/bot/bot.py
- aiogram/dispatcher/handler.py
- aiogram/dispatcher/webhook.py
- aiogram/utils/text_decorations.py
This closes #456.
Removed all redundant definitions. This resolves #456. 
Passed existing unit tests locally.
* Operating System: macOS Big Sur 11.2
> Removed redundant definitions

- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/filters/__init__.py
- aiogram/dispatcher/filters/builtin.py
- docs/source/dispatcher/filters.rst
Add a brand new filter for media groups. Taking the latest Telegram Bot API updates into account, this filter might be quite useful for more and more people in the future.
* Operating System: Ubuntu 20.04
* Python version: 3.8.5
> Add MediaGroup Filter

- aiogram/types/chat.py
Add delete_message shortcut for Chat
> Add delete_message shortcut for Chat

- aiogram/types/document.py
Useful properties to deal with documents
On my bot
> Add mime types parsing to Document

- examples/text_filter_example.py
Fixed weird description for text example
> Fixed example description

- README.md
- README.rst
- aiogram/__init__.py
- aiogram/bot/api.py
- aiogram/bot/bot.py
- aiogram/types/__init__.py
- aiogram/types/chat.py
- aiogram/types/inline_query.py
- aiogram/types/input_message_content.py
- aiogram/types/message.py
- aiogram/types/voice_chat_scheduled.py
- docs/source/index.rst
> Telegram API 5.2 support

- aiogram/utils/deep_linking.py
- tests/test_utils/test_deep_linking.py
- fixed cases with ValueError before encoding
- fixed test cases
- refactored (code style, redundant functions, e.t.c.)
- example enriched
> Deep linking util fix

- aiogram/contrib/middlewares/i18n.py
Fixes #544 
- [х] Bug fix (non-breaking change which fixes an issue)
> i18n get_locale without User

- aiogram/contrib/fsm_storage/memory.py
- aiogram/contrib/fsm_storage/mongo.py
- aiogram/contrib/fsm_storage/redis.py
- aiogram/contrib/fsm_storage/rethinkdb.py
- aiogram/dispatcher/storage.py
> Set state via storage

- aiogram/types/update.py
Specify an empty list to receive all update types except chat_member (default)
Fixes #588
> Fix default updates

- aiogram/types/chat_member.py
Fixes ChatMember status checks 
More: https://t.me/aiogram_ru/681208
> ChatMember status check fix

- aiogram/types/fields.py
> Optional ListField serialize/deserialize fix

- aiogram/types/base.py
- aiogram/types/chat_member.py
- aiogram/types/fields.py
> Add ability to make custom deserialization for Telegram objects

- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/filters/builtin.py
- aiogram/dispatcher/webhook.py
- aiogram/types/inline_keyboard.py
- aiogram/types/input_file.py
- aiogram/types/message_entity.py
- aiogram/types/reply_keyboard.py
- aiogram/utils/callback_data.py
- aiogram/utils/helper.py
- Removed unnecessary else clauses
- Merged isinstance calls
- Simplified sequence comparison
- Replaced if statements with if expressions
- Merged else clause's nested if statement into elif
Refactoring.
> Simplify some conditions

- aiogram/types/base.py
yield from is semantically identical to a for loop with a yield inside. But it is more readable.
Refactoring.
> Replace yield inside for loop with yield from

- aiogram/contrib/fsm_storage/mongo.py
- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/filters/factory.py
- aiogram/dispatcher/filters/filters.py
- aiogram/types/fields.py
- aiogram/types/inline_keyboard.py
- aiogram/types/reply_keyboard.py
- aiogram/utils/helper.py
For loops with .append() or .extend() were replaced with list comprehensions where possible to improve performance a little bit.
Refactoring.
> Replace for loops with comprehensions

- aiogram/types/__init__.py
fix: add missed ChatMember{x} in types
> fix: add missed ChatMember{x} in types

- aiogram/dispatcher/event/telegram.py
- tests/test_api/test_methods/test_delete_my_commands.py
- tests/test_api/test_methods/test_get_chat_administrators.py
- tests/test_api/test_methods/test_get_chat_member.py
- tests/test_dispatcher/test_dispatcher.py
- tests/test_dispatcher/test_handler/test_chat_member.py
> Fix outer_middleware resolution (#637)

- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/event/bases.py
- aiogram/dispatcher/event/telegram.py
- aiogram/dispatcher/filters/command.py
- aiogram/dispatcher/filters/exception.py
- aiogram/dispatcher/fsm/storage/redis.py
- aiogram/dispatcher/router.py
- poetry.lock
- pyproject.toml
- tests/test_api/test_methods/test_delete_my_commands.py
- tests/test_dispatcher/test_event/test_telegram.py
- tests/test_dispatcher/test_filters/test_exception.py
- tests/test_dispatcher/test_router.py
Added possibility to specify global filters for router
> Global filters for router

- CHANGES.rst
- CHANGES/.template.rst.jinja2
- CHANGES/602.doc
- HISTORY.rst
- Makefile
- docs/changelog.rst
- docs/index.rst
- poetry.lock
- pyproject.toml
Added integration with `towncrier`
Fixes #602 
- Manually
> `towncrier` integration

- .editorconfig
- CHANGES/650.misc
Add ability to automatically apply project settings on developers IDE
Fixes #650
> Add `.editorconfig` support 

- CHANGES/651.misc
- aiogram/dispatcher/fsm/storage/redis.py
> Redis storage speedup globals

- aiogram/contrib/fsm_storage/redis.py
- docs/source/dispatcher/fsm.rst
We should add non-compatibility-breakable support for aioredis v2
Fixes #648
> aioredis v2 support

- CHANGES/663.misc
- aiogram/types/message.py
add allow_sending_without_reply param to Message reply aliases
* Python version: 3.9.1
> add allow_sending_without_reply param to Message reply aliases

- CHANGES/660.bugfix
- aiogram/methods/answer_inline_query.py
- tests/test_api/test_methods/test_answer_inline_query.py
Prepare parse mode for input_message_content of InlineQueryesult
Fixes #660
* Python version: 3.9.1
> fix #660 prepare parse mode for input_message_content

- aiogram/types/user.py
Add type hints to `url` & `get_mention` in `User`
> Add type hints to `url` & `get_mention` in `User`

- aiogram/contrib/fsm_storage/redis.py
Current version returns bytes for every request
> Decode aioredis v2 responses

- CHANGES/669.misc
- aiogram/dispatcher/dispatcher.py
- aiogram/types/update.py
- aiogram/utils/mypy_hacks.py
Move update type detecting from `Dispatcher` to `Update`
* Python version: 3.9.2
> Move update type detecting from `Dispatcher` to `Update`

- aiogram/types/mixins.py
- tests/types/test_mixins.py
Fix  dirs creating, add separate parametrs for saving to directory and file
The depracation mark on destination parametr is negotiable.
Fixes #665
* Operating System: Win10 
* Python version: 3.9.2
> Fix #665, add separate parametrs for saving to directory and file

- .github/workflows/tests.yml
https://github.com/actions/setup-python/releases 
> tests.yml: Upgrade to actions/setup-python@v2

- CHANGES/717.feature
- aiogram/dispatcher/event/telegram.py
- aiogram/exceptions.py
- tests/test_dispatcher/test_event/test_telegram.py
Improved description of filters factory resolving error
Fixes #717
> Improve filters factory resolve error

- aiogram/contrib/fsm_storage/files.py
- aiogram/utils/json.py
- tests/__init__.py
> Reuse json util 

- examples/custom_filter_example.py
New example of using BoundFilter inheritance
> custom filter for filters_factory example

- aiogram/dispatcher/storage.py
- tests/test_dispatcher/test_fsm_context.py
With aiogram branch dev-2.x function FSMContext.update with kwvalues doesn't work
Fixes #754
Test case attached
* Operating System: win10
* Python version: 3.9 and 3.10
> Fix fsmcontextproxy update

- docs/dispatcher/index.rst
> fixed a spelling error in the documentation

- aiogram/dispatcher/webhook.py
> Header values must be str instances

- README.md
- aiogram/__init__.py
- aiogram/bot/api.py
- aiogram/bot/bot.py
- aiogram/types/chat.py
- aiogram/types/message.py
- docs/source/index.rst
> Bot API 5.5

- examples/check_user_language.py
> Remove markdown v1 from examples

- aiogram/bot/bot.py
- aiogram/types/chat.py
- aiogram/utils/deprecated.py
Sometimes Telegram API developers made changes without any info.
E.g.: Special thanks for [@levlam](https://github.com/levlam) for silent Telegram API updates with removing fields.
https://github.com/MarshalX/telegram-crawler/commit/f39ff2e77cebeb821c85ecf9f22b41bd1636523e
> Telegram API silent update

- aiogram/contrib/middlewares/logging.py
> Missing space

- aiogram/dispatcher/fsm/storage/redis.py
- tests/test_dispatcher/test_fsm/storage/test_redis.py
* Operating System: Ubuntu 20.04.3 LTS
* Python version: 3.8.10
> Check destiny in case of no `with_destiny`

- README.md
- aiogram/__init__.py
- aiogram/bot/api.py
- aiogram/bot/bot.py
- aiogram/types/message.py
- aiogram/types/message_entity.py
- aiogram/utils/markdown.py
- aiogram/utils/text_decorations.py
- docs/source/index.rst
> Bot API v5.6 support

- aiogram/contrib/middlewares/fsm.py
> Remove unused code from fsm.py

- aiogram/bot/base.py
- aiogram/bot/bot.py
- aiogram/dispatcher/webhook.py
- aiogram/types/input_message_content.py
> Global disable web page preview parameter

- README.rst
Bot API Version update in docs
> docs: bot API version update

- aiogram/types/chat_join_request.py
Fixed to Bot API documentation in docstring
> Fixed to Bot API documentation in docstring

- examples/separate_api_route_example.py
> Typo fix in example: Use hardcoded token as in the other examples

- README.md
- README.rst
- aiogram/__init__.py
- aiogram/bot/api.py
- aiogram/bot/bot.py
- aiogram/types/sticker.py
- aiogram/types/sticker_set.py
- docs/source/index.rst
https://core.telegram.org/bots/api-changelog#january-31-2022
> Updated to Bot API 5.7

- aiogram/bot/base.py
- tests/test_bot/test_bot_download_file.py
- tests/types/test_mixins.py
> [2.x] Don't save error as a file

- aiogram/types/input_message_content.py
> Fixed issue 812

- docs/utils/i18n.rst
> Fix I18nMiddleware class in i18n docs

- setup.py
Changed requires_python to python_requires
Fixes #885
> Fix `python_requires` tag in `setup.py`

- aiogram/utils/i18n/middleware.py
user.language_code is Optional and may raise an exception
Fixes #870
> fix: User.language_code is optional

- docs/dispatcher/filters/chat_member_updated.rst
- docs/dispatcher/filters/magic_data.rst
- docs/dispatcher/filters/magic_filters.rst
- examples/echo_bot.py
- examples/finite_state_machine.py
- examples/multibot.py
- examples/specify_updates.py
- [Update magic_data Allowed handlers](https://github.com/aiogram/aiogram/commit/7733db81702140d35b181d14cbf17b576ad854e9)
- [Fix ChatMemberUpdated example](https://github.com/aiogram/aiogram/commit/8248bbaa77d1d55dd4bc0e721918e2b77a21a4f9)
- [Fix examples with .in_(...) and delete with @](https://github.com/aiogram/aiogram/commit/39ca3e8fcfc3de70cbfdf92e47b3fb75c2588f4c)
- [Fix commands in examples](https://github.com/aiogram/aiogram/commit/ad4ccac8f7db470d6eb76b676fb4b7dbaab67f9b)
> Fix docs and examples

- docs/dispatcher/dispatcher.rst
Fixed typo Dispathcer
Fixed typo
> Dispathcer to Dispatcher on docs

- CHANGES/894.feature.rst
- aiogram/dispatcher/event/event.py
- aiogram/dispatcher/event/handler.py
- aiogram/dispatcher/event/telegram.py
- aiogram/dispatcher/filters/__init__.py
- aiogram/dispatcher/filters/base.py
- aiogram/dispatcher/filters/logic.py
- aiogram/dispatcher/middlewares/manager.py
- aiogram/dispatcher/router.py
- tests/test_dispatcher/test_filters/test_logic.py
> Added possibility to combine filters or invert result

- CHANGES/907.misc.rst
- aiogram/dispatcher/filters/command.py
Changed CommandPatterType to CommandPatternType
Supposedly, the implied word is patterN
> Small typo fix

- .github/workflows/tests.yml
Note that I haven't tested this
> Skip running tests when there are no code or test changes

- aiogram/dispatcher/storage.py
Fix #970
- Operating system: Ubuntu 20.04 LTS
- Python version: 3.8
> Change set_data to set_bucket in reset_bucket (#970)

- aiogram/types/chat_administrator_rights.py
Added constructor for ChatAdministratorRights
> Added constructor for ChatAdministratorRights

- CHANGES/942.misc.rst
- aiogram/dispatcher/event/telegram.py
- aiogram/filters/__init__.py
- docs/dispatcher/filters/chat_member_updated.rst
- docs/dispatcher/filters/command.rst
- docs/dispatcher/filters/index.rst
- docs/dispatcher/filters/magic_data.rst
- examples/echo_bot.py
- examples/finite_state_machine.py
- examples/specify_updates.py
- tests/test_dispatcher/test_event/test_telegram.py
Deprecate filters factory as described in #942
> Deprecate filters factory

- CHANGES/988.feature
- aiogram/exceptions.py
- tests/test_api/test_types/test_exception.py
> Add representation for aiogram exception

- dev_requirements.txt
- tests/conftest.py
- tests/contrib/fsm_storage/test_storage.py
- tests/test_bot.py
- tests/test_bot/test_bot_download_file.py
- tests/test_dispatcher/test_filters/test_state.py
- tests/test_message.py
- tests/test_utils/test_auth_widget.py
- tests/test_utils/test_markdown.py
- tests/types/dataset.py
- tests/types/test_mixins.py
- applied `pytest_async`
- fixed `dev_requirements.txt`
- minor typos
Tests passed
- Operating system: MacOS
- Python version: 3.9
> Recover tests

- LICENSE
Update year range in LICENSE file
> Update year range in license

- docs/dispatcher/filters/index.rst
Just found and fixed `Unresolved reference 'chat_type'`
> Fix chat type example

- aiogram/types/chat_member.py
- tests/types/dataset.py
Add field `can_manage_video_chats` to `ChatMemberOwner`
No tests, just add field
- Operating system: Win10
- Python version: 3.9.*
> Add field `can_manage_video_chats` to ChatMemberOwner

- CHANGES/1017.doc
- CHANGES/1017.doc.rst
- CHANGES/1018.feature.rst
- aiogram/filters/__init__.py
- aiogram/filters/base.py
- aiogram/filters/callback_data.py
- aiogram/filters/chat_member_updated.py
- aiogram/filters/command.py
- aiogram/filters/exception.py
- aiogram/filters/logic.py
- aiogram/filters/magic_data.py
- aiogram/filters/state.py
- aiogram/filters/text.py
- docs/dispatcher/filters/index.rst
- docs/locale/en/LC_MESSAGES/api/upload_file.po
- docs/locale/en/LC_MESSAGES/changelog.po
- docs/locale/en/LC_MESSAGES/dispatcher/filters/index.po
- docs/locale/en/LC_MESSAGES/dispatcher/filters/magic_data.po
- docs/locale/en/LC_MESSAGES/index.po
- docs/locale/uk_UA/LC_MESSAGES/api/upload_file.po
- docs/locale/uk_UA/LC_MESSAGES/changelog.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/filters/index.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/filters/magic_data.po
- docs/locale/uk_UA/LC_MESSAGES/index.po
- tests/test_filters/test_base.py
- tests/test_filters/test_logic.py
Added And/Or combinations for filters
> Combining filters (again)

- docs/dispatcher/router.rst
> Fix typo in docs dev-3.x

- docs/locale/uk_UA/LC_MESSAGES/dispatcher/flags.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/index.po
Переклад flags на Українську мову
> Translate flags docs page to uk_UA

- docs/locale/uk_UA/LC_MESSAGES/dispatcher/finite_state_machine/index.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/finite_state_machine/storages.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/middlewares.po
UA translation of FSM & Middlewares docs
- Operating system: e.g. Ubuntu 20.04.2 LTS
-Python version: e.g. 3.10.1
> UA translation of FSM & Middlewares docs

- .github/ISSUE_TEMPLATE/feature.yaml
Add `aiogram version` dropdown field to feature request template. Feature request may be relevant either to v2 or v3, so ask a user about the version they use and want to improve.
> Add `aiogram version` field to feature request template

- CHANGES/1064.bugfix.rst
- aiogram/types/message.py
Fix for copy and forwarding in special topic
--
- Operating system: Windows 10 x64
-Python version: Python 3.10
> Fix for copy and forwarding in special topic

- aiogram/dispatcher/filters/builtin.py
- aiogram/types/chat.py
Added missing ChatJoinRequest to check function of a ChatTypeFilter
chat_join_request_handlers were already added to event_handlers for ChatTypeFilter, but check for ChatJoinRequest type was missing inside check function in ChatTypeFilter.
> Dev 2.x chat_type filter fix

- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/base.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/callback_query.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/chat_member.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/chosen_inline_result.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/error.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/index.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/inline_query.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/message.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/poll.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/pre_checkout_query.po
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/shipping_query.po
UA translation of class based handlers docs
Documentation translation
> UA translation of class based handlers docs

- CHANGES/1106.bugfix.rst
- aiogram/filters/command.py
- tests/test_filters/test_command.py
Bug fix https://github.com/aiogram/aiogram/issues/1106
> ignore_case fix for aiogram.filters.command.Command()

- docs/locale/uk_UA/LC_MESSAGES/api/enums/bot_command_scope_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/chat_member_status.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/chat_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/content_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/dice_emoji.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/index.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/inline_query_result_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/input_media_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/mask_position_point.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/menu_button_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/message_entity_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/parse_mode.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/poll_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/sticker_type.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/topic_icon_color.po
- docs/locale/uk_UA/LC_MESSAGES/api/enums/update_type.po
Updated all texts in the enums folder
sphinx-autobuild --watch aiogram/ docs/ docs/_build/ -D language=uk_UA
- Operating system: e.g. Ubuntu 20.04.2 LTS
-Python version: e.g. 3.10.1
> update ua docs: patch api/enums/*.po

- CHANGES/1124.misc.rst
- Makefile
- aiogram/dispatcher/dispatcher.py
- aiogram/dispatcher/flags.py
- aiogram/exceptions.py
- pyproject.toml
- tests/test_dispatcher/test_dispatcher.py
Reworked graceful shutodwn
(Pull-request will be explained in more detail soon)
> Reworked graceful shutdown

- CHANGES/1133.doc.rst
- docs/api/upload_file.rst
Tiny grammar typos for upload file doc.
Automatically initiated from docs page.
N/A
> Update upload_file.rst | tiny grammar typos

- aiogram/utils/deep_linking.py
Changes in deep_linking module examples
> Update deep_linking basic examples

- CHANGES/1147.feature
- aiogram/dispatcher/event/telegram.py
- aiogram/dispatcher/router.py
- tests/test_dispatcher/test_router.py
* Operating System: Ubuntu 20.04.1
* Python version: 3.8.16
> skip if current router does not have observer for custom event

- CHANGES/1162.bugfix.rst
- aiogram/dispatcher/dispatcher.py
- pyproject.toml
- tests/test_dispatcher/test_dispatcher.py
Fixed compatibility with Python 3.8-3.9
> Fix compatibility with Python 3.8-3.9

- CHANGES/1163.feature.rst
- aiogram/filters/callback_data.py
- tests/test_filters/test_callback_data.py
> Improve callback data serialization

- CHANGES/1196.bugfix.rst
- aiogram/dispatcher/dispatcher.py
- aiogram/webhook/aiohttp_server.py
Fixed workflow data propagation
> Fixed workflow data propagation

- CHANGES/1191.feature.rst
- aiogram/__init__.py
- aiogram/__meta__.py
- aiogram/client/session/aiohttp.py
- aiogram/client/session/base.py
- aiogram/types/input_file.py
- pyproject.toml
- scripts/bump_versions.py
- tests/mocked_bot.py
- tests/test_api/test_client/test_session/test_base_session.py
Added possibility to pass custom headers to URLInputFile object
Fixes #1191
> Added possibility to pass custom headers to URLInputFile object

- docs/contributing.rst
Related to: https://github.com/aiogram/aiogram/commit/68a6c2c192904562bf5a5a6171b59eaf77774e33
> Remove patreon from docs/contributing.rst

- .butcher/types/ChatMemberUpdated/aliases.yml
- CHANGES/1234.feature.rst
- aiogram/types/chat_member_updated.py
- docs/api/methods/send_animation.rst
- docs/api/methods/send_audio.rst
- docs/api/methods/send_contact.rst
- docs/api/methods/send_dice.rst
- docs/api/methods/send_document.rst
- docs/api/methods/send_game.rst
- docs/api/methods/send_invoice.rst
- docs/api/methods/send_location.rst
- docs/api/methods/send_media_group.rst
- docs/api/methods/send_message.rst
- docs/api/methods/send_photo.rst
- docs/api/methods/send_poll.rst
- docs/api/methods/send_sticker.rst
- docs/api/methods/send_venue.rst
- docs/api/methods/send_video.rst
- docs/api/methods/send_video_note.rst
- docs/api/methods/send_voice.rst
- tests/test_api/test_methods/test_send_message.py
- tests/test_api/test_types/test_chat_member_updated.py
Added shortcuts for ChatMemberUpdate event
> Added shortcuts for ChatMemberUpdate event

- .butcher/types/ChatJoinRequest/aliases.yml
- CHANGES/1234.feature.rst
- CHANGES/1235.feature.rst
- aiogram/types/chat_join_request.py
- docs/api/methods/send_animation.rst
- docs/api/methods/send_audio.rst
- docs/api/methods/send_contact.rst
- docs/api/methods/send_dice.rst
- docs/api/methods/send_document.rst
- docs/api/methods/send_game.rst
- docs/api/methods/send_invoice.rst
- docs/api/methods/send_location.rst
- docs/api/methods/send_media_group.rst
- docs/api/methods/send_message.rst
- docs/api/methods/send_photo.rst
- docs/api/methods/send_poll.rst
- docs/api/methods/send_sticker.rst
- docs/api/methods/send_venue.rst
- docs/api/methods/send_video.rst
- docs/api/methods/send_video_note.rst
- docs/api/methods/send_voice.rst
- tests/test_api/test_types/test_chat_join_request.py
- tests/test_api/test_types/test_chat_member_updated.py
Added new shortcuts for `ChatJoinRequest`
to make easier access to sending messages to users who wants to join to chat.
> Chat join request shortcuts

- CHANGES/1238.misc.rst
- aiogram/client/session/aiohttp.py
- aiogram/types/input_file.py
- aiogram/webhook/aiohttp_server.py
- tests/test_api/test_client/test_session/test_aiohttp_session.py
- tests/test_api/test_types/test_chat_join_request.py
- tests/test_api/test_types/test_input_file.py
> Reworked InputFile sending

- .butcher/types/Message/aliases.yml
- .butcher/types/PreCheckoutQuery/aliases.yml
- .butcher/types/ShippingQuery/aliases.yml
- CHANGES/#1244.bugfix.rst
- aiogram/types/message.py
- aiogram/types/pre_checkout_query.py
- aiogram/types/shipping_query.py
Added codegen configuration for lost shortcuts:
- ShippingQuery.answer
- PreCheckoutQuery.answer
- Message.delete_reply_markup
> Added codegen configuration for lost shortcuts

- CHANGES/1249.feature.rst
- aiogram/utils/chat_action.py
- tests/test_utils/test_chat_action.py
Added support for message_thread_id in ChatActionSender
Fixes #1249
> Added support for message_thread_id in ChatActionSender

- CHANGES/1251.doc.rst
- docs/migration_2_to_3.rst
Added a few words about skipping pending updates
> Added a few words about skipping pending updates

- CHANGES/1264.doc.rst
- docs/migration_2_to_3.rst
> Migration FAQ supplement (Finite State Machine)

- pyproject.toml
Add support for all minor versions of pydantic v2
Fixes #1271
CI/CD tests only
> Support wider pydantic version

- CHANGES/1284.bugfix.rst
- aiogram/types/message.py
SendSticker is not mounted to bot instance
> Fixed method :code:`Message.send_copy` for stickers

- docs/migration_2_to_3.rst
> Updated migration guide with API server

- .github/workflows/pull_request_changelog.yml
> New towncrier docs link

- tests/test_api/test_types/test_reply_keyboard_remove.py
> Update deprecated pydantic fields access

- .github/PULL_REQUEST_TEMPLATE.md
- aiogram/client/session/aiohttp.py
- aiogram/fsm/storage/redis.py
- pyproject.toml
- tests/test_api/test_client/test_bot.py
- tests/test_api/test_client/test_session/test_aiohttp_session.py
- tests/test_api/test_types/test_input_file.py
- tests/test_dispatcher/test_dispatcher.py
- tests/test_filters/test_exception.py
- tests/test_fsm/storage/test_isolation.py
- tests/test_utils/test_chat_action.py
- tests/test_utils/test_i18n.py
Fixes #1310
Tests improvement
* Operating System: macOS
> Handle expected warnings & raise unexpected warnings

- aiogram/dispatcher/dispatcher.py
I've been struggling with the mentioned issue a lot, and my Sentry was blowing up with this issue in lots of my bots.
In each of them, I usually call metrics API inside the handler, which is poorly buffered and sometimes not successful or even slow.
Some of my bots are popular enough, so I assume high update volume and slow handlers result in the deallocation of dangling tasks, which results in:
- Tasks are not completed, i.e. last functions in the handler are not called
- Garbage collector messes up everything, and some handlers are unable to complete `current_handler.reset(ctx_token)`, therefore next alive handler pick-ups Context and can't do anything with it
This PR implements reference saving for `_process_polling_updates` Tasks as described in [Python …
> [2.x] Save `_process_polling_updates` from being garbage collected (fixes #628 #927)

- .readthedocs.yml
Updated & Fixed ReadTheDocs configuration
> Update ReadTheDocs configuration

- CHANGES/1360.bugfix.rst
- aiogram/dispatcher/event/telegram.py
- tests/test_api/test_types/test_message.py
Add current handler to filters, so that flags can be retrieved from it.
> Add current handler to filters, so that flags can be retrieved from it.

- CHANGES/1353.doc.rst
- docs/api/session/middleware.rst
> chore(docs): update middleware.rst

- CHANGES/1369.feature.rst
- tests/test_fsm/test_scene.py
Add tests for scenes (not ready)
* Python version: 3.10.*
> Scenes Tests

- aiogram/fsm/scene.py
- tests/test_fsm/test_scene.py
ADD tests for `SceneWizard`
ADD tests for `Scenes`
ADD tests for `HistoryManager`
> Scenes Tests. Part 2

- CHANGES/1424.bugfix.rst
- docs/locale/uk_UA/LC_MESSAGES/utils/web_app.po
- docs/utils/web_app.rst
- [ x ] Documentation (typos, code examples or any documentation update)
- [ x ] I have made corresponding changes to the documentation
> doc added for missing Telegram WebApp API classes and fields

- CHANGES/1436.bugfix.rst
- aiogram/dispatcher/middlewares/user_context.py
- tests/test_api/test_client/test_bot.py
- tests/test_api/test_client/test_default.py
Fixed poll answer FSM context by handling`voter_chat` for`poll_answer` event
> Fixed poll answer FSM context

- examples/echo_bot.py
Added DefaultBotProperties and cleaned imports for a bit.
Code checked with black, isort, mypy
* Operating System: ubuntu 22.04
* Python version: 3.10
> Add default bot properties and clean imports

- .github/workflows/pull_request_changelog.yml
- .github/workflows/pypi-release.yml
- .github/workflows/tests.yml
Bumped deprecated actions versions
> Bump actions versions

- CHANGES/1460.misc.rst
- pyproject.toml
> loosened pydantic upper bound to <2.8

- docs/dispatcher/dispatcher.rst
> docs: Correct a typo error

- CHANGES/1412.doc.rst
- docs/migration_2_to_3.rst
Added message serialisation and deserialization block in 2.x -> 3.x migration guide
Added description of a new way to serialize and deserialize Message objects.
Fixes #1412
* Python version: 3.10
> Added message serialisation and deserialization block in 2.x -> 3.x migration guide

- CHANGES/1496.bugfix.rst
- aiogram/utils/text_decorations.py
- tests/test_utils/test_text_decorations.py
Fixes #1496 
* Operating System: windows 11
> Fixed bug with wrong MarkdownV2 custom emoji parsing

- CHANGES/1504.doc.rst
- docs/migration_2_to_3.rst
Added info about dependency changes
P.S.: also file was auto-reformatted with pre-commit 🤷‍♂️
> Add Dependencies to migrations guide

- docs/api/upload_file.rst
> `InputFile` reuse recommendations update

- CHANGES/1519.doc.rst
- docs/dispatcher/finite_state_machine/scene.rst
> Corrected typo

- aiogram/types/external_reply_info.py
- aiogram/types/message.py
- aiogram/types/star_transaction.py
- examples/multibot.py
- tests/test_api/test_types/test_message.py
> Fixed tests

- pyproject.toml
Bump pydantic support to v2.8
pytest
> Bump pydantic to v2.8

- .editorconfig
- docs/dispatcher/dispatcher.rst
- docs/migration_2_to_3.rst
> Migrating feeding updates (docs)

- .butcher/schema/schema.json
- .butcher/types/Message/entity.json
- .butcher/types/RefundedPayment/entity.json
- CHANGES/1536.feature.rst
- aiogram/enums/content_type.py
- aiogram/types/__init__.py
- aiogram/types/message.py
- aiogram/types/refunded_payment.py
- docs/api/types/index.rst
- docs/api/types/refunded_payment.rst
- tests/test_api/test_types/test_message.py
Added full support of [Bot API 7.7](https://core.telegram.org/bots/api-changelog#july-7-2024)
> Added full support of Bot API 7.7

- aiogram/utils/formatting.py
- examples/multibot.py
- examples/web_app/routes.py
Current version failed with ruff checker, so I fixed it
> Fixed ruff issues

- CHANGES/1548.misc.rst
- pyproject.toml
Related comment:
https://github.com/aiogram/aiogram/issues/1500#issuecomment-2259610379_
GitHub CI
> Added aiohttp 3.10 support

- CHANGES/1576.feature.rst
- pyproject.toml
Increase max pydantic version support
> Increase `pydantic` max version (`<2.9` -> `<2.10`)

- CHANGES/1583.feature.rst
- aiogram/fsm/scene.py
- tests/test_fsm/test_scene.py
Enhanced the inheritance of handlers and actions in scenes. Refactored to eliminate the copying of previously connected handlers and actions from parent scenes. Now, handlers are dynamically rebuilt based on the current class, properly utilizing class inheritance and enabling handler overrides.
Fixes: #1583
> Improved Scene handler and action inheritance mechanism

- .github/workflows/tests.yml
- CHANGES/1589.misc.rst
- pyproject.toml
- tests/test_api/test_client/test_session/test_aiohttp_session.py
- tests/test_dispatcher/test_dispatcher.py
- tests/test_utils/test_callback_answer.py
- tests/test_utils/test_chat_action.py
Enabled testing on Python 3.13 
Dropped compatibilit with Python 3.8
> Enabled tests on Python 3.13, disabled on Python 3.8

- CHANGES.rst
Fix link formatting for Bot API 8.1 support in CHANGES.rst
> Fix link formatting

- CHANGES/1612.misc.rst
- aiogram/client/bot.py
- aiogram/client/telegram.py
- tests/test_api/test_client/test_api_server.py
- tests/test_api/test_client/test_bot.py
> Remove path to string convertion

- CHANGES/1634.doc.rst
- docs/dispatcher/class_based_handlers/base.rst
- docs/locale/uk_UA/LC_MESSAGES/dispatcher/class_based_handlers/base.po
Fixed annotations for page `Class based handlers / BaseHandler`
- https://docs.aiogram.dev/uk-ua/dev-3.x/dispatcher/class_based_handlers/base.html
> Docs: Fix annotations

- CHANGES/1664.bugfix.rst
- aiogram/webhook/aiohttp_server.py
- tests/test_webhook/test_aiohtt_server.py
> fix empty response into webhook

- CHANGES/1677.misc.rst
- aiogram/utils/keyboard.py
> Fix for #1677

- CHANGES/1681.misc.rst
- pyproject.toml
> Pin Babel's major version

- .github/workflows/tests.yml
- CHANGES/1715.feature.rst
- aiogram/utils/web_app_signature.py
- pyproject.toml
- tests/test_utils/test_web_app_signature.py
https://core.telegram.org/bots/webapps#validating-data-for-third-party-use
Feature
> Support validating init data using only bot id.
